// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ClusterRole is a cluster level, logical grouping of PolicyRules that can be referenced as a unit by a RoleBinding or ClusterRoleBinding.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClusterRole {
    /// aggregationRule is an optional field that describes how to build the Rules for this ClusterRole. If AggregationRule is set, then the Rules are controller managed and direct changes to Rules will be stomped by the controller.
    #[serde(rename = "aggregationRule", default, skip_serializing_if = "Option::is_none")]
    pub aggregation_rule: Option<crate::io::k8s::api::rbac::v1::AggregationRule>,

    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `rbac.authorization.k8s.io/v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `ClusterRole`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// metadata is the standard object's metadata.
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ObjectMeta>,

    /// rules holds all the PolicyRules for this ClusterRole
    #[serde(rename = "rules", default, skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<crate::io::k8s::api::rbac::v1::PolicyRule>>,
}

impl ClusterRole {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "rbac.authorization.k8s.io/v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "ClusterRole";
}

impl Default for ClusterRole {
    fn default() -> Self {
        Self {
            aggregation_rule: None,
            api_version: Some(Self::API_VERSION.to_string()),
            kind: Some(Self::KIND.to_string()),
            metadata: None,
            rules: None,
        }
    }
}

/// ClusterRoleList is a collection of ClusterRoles
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClusterRoleList {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `rbac.authorization.k8s.io/v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// Items is a list of ClusterRoles
    #[serde(rename = "items", default, skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::io::k8s::api::rbac::v1::ClusterRole>>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `ClusterRoleList`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard object's metadata.
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ListMeta>,
}

impl ClusterRoleList {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "rbac.authorization.k8s.io/v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "ClusterRoleList";
}

impl Default for ClusterRoleList {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            items: None,
            kind: Some(Self::KIND.to_string()),
            metadata: None,
        }
    }
}
