// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// APIResource specifies the name of a resource and whether it is namespaced.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct APIResource {
    /// categories is a list of the grouped resources this resource belongs to (e.g. 'all')
    #[serde(rename = "categories", default, skip_serializing_if = "Option::is_none")]
    pub categories: Option<Vec<String>>,

    /// group is the preferred group of the resource.  Empty implies the group of the containing resource list. For subresources, this may have a different value, for example: Scale".
    #[serde(rename = "group", default, skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,

    /// kind is the kind for the resource (e.g. 'Foo' is the kind for a resource 'foo')
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// name is the plural name of the resource.
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// namespaced indicates if a resource is namespaced or not.
    #[serde(rename = "namespaced", default, skip_serializing_if = "Option::is_none")]
    pub namespaced: Option<bool>,

    /// shortNames is a list of suggested short names of the resource.
    #[serde(rename = "shortNames", default, skip_serializing_if = "Option::is_none")]
    pub short_names: Option<Vec<String>>,

    /// singularName is the singular name of the resource.  This allows clients to handle plural and singular opaquely. The singularName is more correct for reporting status on a single item and both singular and plural are allowed from the kubectl CLI interface.
    #[serde(rename = "singularName", default, skip_serializing_if = "Option::is_none")]
    pub singular_name: Option<String>,

    /// The hash value of the storage version, the version this resource is converted to when written to the data store. Value must be treated as opaque by clients. Only equality comparison on the value is valid. This is an alpha feature and may change or be removed in the future. The field is populated by the apiserver only if the StorageVersionHash feature gate is enabled. This field will remain optional even if it graduates.
    #[serde(rename = "storageVersionHash", default, skip_serializing_if = "Option::is_none")]
    pub storage_version_hash: Option<String>,

    /// verbs is a list of supported kube verbs (this includes get, list, watch, create, update, patch, delete, deletecollection, and proxy)
    #[serde(rename = "verbs", default, skip_serializing_if = "Option::is_none")]
    pub verbs: Option<Vec<String>>,

    /// version is the preferred version of the resource.  Empty implies the version of the containing resource list For subresources, this may have a different value, for example: v1 (while inside a v1beta1 version of the core resource's group)".
    #[serde(rename = "version", default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}
