// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// Preconditions must be fulfilled before an operation (update, delete, etc.) is carried out.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Preconditions {
    /// Specifies the target ResourceVersion
    #[serde(rename = "resourceVersion", default, skip_serializing_if = "Option::is_none")]
    pub resource_version: Option<String>,

    /// Specifies the target UID.
    #[serde(rename = "uid", default, skip_serializing_if = "Option::is_none")]
    pub uid: Option<String>,
}
