// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ShardInfo describes the shard selector that was applied to produce a list response. Its presence on a list response indicates the list is a filtered subset.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ShardInfo {
    /// selector is the shard selector string from the request, echoed back so clients can verify which shard they received and merge responses from multiple shards.
    #[serde(rename = "selector", default, skip_serializing_if = "Option::is_none")]
    pub selector: Option<String>,
}
