// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
pub type Time = String;
