// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// Event represents a single event to a watched resource.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WatchEvent {
    /// Object is:
    ///  * If Type is Added or Modified: the new state of the object.
    ///  * If Type is Deleted: the state of the object immediately before deletion.
    ///  * If Type is Error: *Status is recommended; other types may make sense
    ///    depending on context.
    #[serde(rename = "object", default, skip_serializing_if = "Option::is_none")]
    pub object: Option<crate::io::k8s::apimachinery::pkg::runtime::RawExtension>,

    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}
