// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// Input configures which WebAssembly module function-wasm runs, what the
/// composition author's own policy layer permits, what a run may consume, and
/// what the module receives. What a module may do beyond the default sandbox
/// is decided per capability by three AND-combined layers
/// (docs/one-pager-three-layer-authz.md): the module's manifest requests it,
/// the Input's compositionPolicy permits it, and the operator's
/// --sandbox-policy-file permits it.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Input {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `wasm.fn.crossplane.io/v1beta1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// CompositionPolicy is the composition author's own Cedar policy layer,
    /// as policy text over the same schema as the operator's
    /// --sandbox-policy-file (actions pullModule, spendCredential,
    /// grantEgress, usePrivateTmp, setEnv; a Request principal carrying
    /// namespace and xrKind; Repository, HostPattern, Capability and
    /// Credential entities). It is AND-combined with the module's manifest
    /// and the operator's policy, so it can only narrow. Two regimes: a
    /// sandbox action it scopes no rule for is not narrowed (the operator and
    /// the manifest decide alone), while a module the composite resource
    /// chooses (module.from) is refused unless a pullModule permit matches
    /// its repository - and may spend a step credential only where a
    /// spendCredential permit matches. Read from the Input only - never
    /// through module.from - so an XR author may pick the module, not widen
    /// the policy. Malformed Cedar is a fatal result at admission.
    #[serde(rename = "compositionPolicy", default, skip_serializing_if = "Option::is_none")]
    pub composition_policy: Option<String>,

    /// Config is passed to the module verbatim as part of its request input.
    /// The runtime does not interpret it; a Go guest reads it with
    /// wasmfn.GetConfig. Non-secret module configuration belongs here - the
    /// module's environment is its manifest's requires.env credential
    /// bindings, never Input-authored values.
    #[serde(rename = "config", default, skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `Input`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Limits narrow what this step's run may consume below the runtime's
    /// ceilings (--module-timeout, --module-memory-limit). Asking for more
    /// than a ceiling is a fatal result naming both. Read from the Input only.
    #[serde(rename = "limits", default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<InputLimits>,

    /// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ObjectMeta>,

    /// Module locates the WebAssembly module to run.
    #[serde(rename = "module", default, skip_serializing_if = "Option::is_none")]
    pub module: Option<InputModule>,
}

impl Input {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "wasm.fn.crossplane.io/v1beta1";

    /// The kind of this resource.
    pub const KIND: &'static str = "Input";
}

impl Default for Input {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            composition_policy: None,
            config: None,
            kind: Some(Self::KIND.to_string()),
            limits: None,
            metadata: None,
            module: None,
        }
    }
}

/// Limits narrow what this step's run may consume below the runtime's
/// ceilings (--module-timeout, --module-memory-limit). Asking for more
/// than a ceiling is a fatal result naming both. Read from the Input only.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InputLimits {
    /// Concurrency caps how many runs of this step execute at once, across
    /// all requests. A further request waits for a slot under its own
    /// context; when the deadline passes first, it is a fatal result that
    /// consumed nothing and is not counted as a run. Keyed by the module's
    /// content digest, so two Compositions using the same module share the
    /// limit. A value above --max-concurrent-runs is silently capped. No
    /// ceiling flag: this only narrows.
    #[serde(rename = "concurrency", default, skip_serializing_if = "Option::is_none")]
    pub concurrency: Option<i32>,

    /// Memory caps the guest's linear memory, e.g. "128Mi"; at most
    /// --module-memory-limit. A guest that grows past it sees memory.grow
    /// fail (a Go guest panics), which ends the run as a fatal result.
    #[serde(rename = "memory", default, skip_serializing_if = "Option::is_none")]
    pub memory: Option<serde_json::Value>,

    /// Timeout is the wall-clock budget of one run, e.g. "5s" or "1m30s"; at
    /// most --module-timeout. The request context's deadline still applies if
    /// shorter.
    #[serde(rename = "timeout", default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
}

/// InputList is a list of Input
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InputList {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// List of inputs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    #[serde(rename = "items", default, skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::io::crossplane::fn_::wasm::v1beta1::Input>>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ListMeta>,
}

/// Module locates the WebAssembly module to run.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InputModule {
    /// AllowEmpty, with From, lets the composite resource leave the field
    /// unset (absent or null): the step then runs no module and returns the
    /// request's desired state and context unchanged - a no-op the pipeline
    /// continues past - instead of a fatal result naming the field. A field
    /// that is set is read, fenced and run exactly as without it. Read from
    /// the Input only, so a composite resource may leave a step empty only
    /// where the Composition allows it. Refused without From: a static
    /// source always resolves.
    #[serde(rename = "allowEmpty", default, skip_serializing_if = "Option::is_none")]
    pub allow_empty: Option<bool>,

    /// From names a field of the observed composite resource, under spec or
    /// status, that holds the source Type names — an {ref, credentials}
    /// object for OCI, an {url, digest} object for HTTP, a string for Path —
    /// e.g. "status.module". The value is read on every request, so each
    /// composite resource can pick its own module; the Input's
    /// compositionPolicy fences what it may pick (pullModule) and spend
    /// (spendCredential). Nothing but the source is read from the composite
    /// resource: compositionPolicy and limits are the Composition's.
    #[serde(rename = "from", default, skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,

    /// HTTP downloads the module from a URL. Set with type HTTP, unless From
    /// names the composite resource field holding the object.
    #[serde(rename = "http", default, skip_serializing_if = "Option::is_none")]
    pub http: Option<InputModuleHttp>,

    /// ManifestPath optionally names the module's wasmfn.yaml manifest file,
    /// relative to --module-dir - the request layer for a Path source
    /// (docs/one-pager-three-layer-authz.md), letting a Path module declare the
    /// capabilities it needs like an OCI artifact does. Valid only with type
    /// Path; without it a Path source carries no manifest and gets only the
    /// default sandbox. Read from the Input only, never through module.from: an
    /// XR author chooses the module file, not what its manifest requests.
    #[serde(rename = "manifestPath", default, skip_serializing_if = "Option::is_none")]
    pub manifest_path: Option<String>,

    /// OCI pulls the module from an OCI registry. Set with type OCI, unless
    /// From names the composite resource field holding the object.
    #[serde(rename = "oci", default, skip_serializing_if = "Option::is_none")]
    pub oci: Option<InputModuleOci>,

    /// Path names a module file relative to the directory the function was
    /// started with (--module-dir); it is refused when that flag is unset.
    /// Meant for local rendering and volume-mounted modules; it carries no
    /// digest. Set with type Path, unless From names the composite resource
    /// field holding the string.
    #[serde(rename = "path", default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,

    /// Type is the kind of source: OCI (an artifact in a registry, the oci
    /// object), HTTP (a URL, the http object) or Path (a file under the
    /// runtime's --module-dir, path). The Composition always chooses the
    /// kind; with From, the composite resource chooses the instance.
    ///
    /// Allowed values: `OCI`, `HTTP`, `Path`.
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

/// HTTP downloads the module from a URL. Set with type HTTP, unless From
/// names the composite resource field holding the object.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InputModuleHttp {
    /// Digest is the sha256 of the module, sha256:<hex>; the download is
    /// verified against it and it addresses the module in the caches.
    #[serde(rename = "digest", default, skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// ManifestDigest is the sha256 of the manifest, sha256:<hex>; the download
    /// is verified against it. Required with ManifestURL, refused without it.
    #[serde(rename = "manifestDigest", default, skip_serializing_if = "Option::is_none")]
    pub manifest_digest: Option<String>,

    /// ManifestURL optionally locates the module's wasmfn.yaml manifest, served
    /// over HTTP(S) beside the module - the module's request layer, authored by
    /// the module author (docs/one-pager-three-layer-authz.md). Without it an
    /// HTTP source carries no manifest and gets only the default sandbox.
    /// ManifestDigest pins it, so it must be set with it. When the source is
    /// chosen by the composite resource (module.from), the manifest URL is
    /// fenced by the compositionPolicy's pullModule rules like the module URL.
    #[serde(rename = "manifestURL", default, skip_serializing_if = "Option::is_none")]
    pub manifest_url: Option<String>,

    /// URL of the module.
    #[serde(rename = "url", default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// OCI pulls the module from an OCI registry. Set with type OCI, unless
/// From names the composite resource field holding the object.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InputModuleOci {
    /// Credentials names a credential of the pipeline step (a Secret) used to
    /// pull the artifact. The Secret carries either a .dockerconfigjson key
    /// or username and password keys. Without it the function's own Docker
    /// config (DOCKER_CONFIG) and anonymous access are tried. An object read
    /// through module.from may name credentials only where the Input's
    /// compositionPolicy permits spendCredential for them on the ref's
    /// repository: the composite resource's author would otherwise choose the
    /// registry host a step credential is sent to.
    #[serde(rename = "credentials", default, skip_serializing_if = "Option::is_none")]
    pub credentials: Option<String>,

    /// Ref is the artifact reference pinned to its manifest digest,
    /// registry/repository@sha256:<hex>, as guestfn push prints it. The
    /// manifest digest pins the module: the manifest names its layer's
    /// digest and every fetch is verified along that chain, so it also
    /// addresses the module in the caches. A tag alone is not accepted: tags
    /// can be moved, and the runtime resolves nothing at request time.
    /// registry/repository:tag@sha256:<hex> is fine — the digest is what is
    /// fetched, the tag is human-readable context.
    #[serde(rename = "ref", default, skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
}
