// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.
#![allow(clippy::all)]
#![allow(non_camel_case_types, non_snake_case)]
#![allow(rustdoc::bare_urls, rustdoc::broken_intra_doc_links, rustdoc::invalid_html_tags)]
#![doc = "Rust models generated by the Crossplane CLI from a project's XRDs and dependencies."]

pub mod com;
pub mod io;
