// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// StorageHealth contains storage backend health reported by a CSI driver on a node.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct StorageHealth {
    /// healthConditions are the adverse storage backend conditions reported by the CSI driver. At most 16 conditions may be reported.
    #[serde(rename = "healthConditions", default, skip_serializing_if = "Option::is_none")]
    pub health_conditions: Option<Vec<crate::io::k8s::api::storage::v1::StorageHealthCondition>>,

    /// name is the CSI driver name, matching CSINodeDriver.name.
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}
