// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// StorageHealthCondition represents an adverse health condition reported by a CSI driver for its storage backend on a node.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct StorageHealthCondition {
    /// accessMode is the access mode affected. Nil means all access modes are affected.
    #[serde(rename = "accessMode", default, skip_serializing_if = "Option::is_none")]
    pub access_mode: Option<String>,

    /// lastTransitionTime is when this condition first appeared at its current state.
    #[serde(rename = "lastTransitionTime", default, skip_serializing_if = "Option::is_none")]
    pub last_transition_time: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::Time>,

    /// message is a human-readable description. Maximum permitted length of a message is 1024 characters.
    #[serde(rename = "message", default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,

    /// reason is a brief CamelCase machine-parseable reason. Maximum permitted length of a reason is 256 characters.
    #[serde(rename = "reason", default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,

    /// status is the health status category. One of "StorageUnreachable", "StorageDegraded".
    #[serde(rename = "status", default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,

    /// volumeMode is the volume mode affected. Nil means both are affected.
    #[serde(rename = "volumeMode", default, skip_serializing_if = "Option::is_none")]
    pub volume_mode: Option<String>,
}
