// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// StorageClass describes the parameters for a class of storage for which PersistentVolumes can be dynamically provisioned.
///
/// StorageClasses are non-namespaced; the name of the storage class according to etcd is in ObjectMeta.Name.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct StorageClass {
    /// allowVolumeExpansion shows whether the storage class allow volume expand.
    #[serde(rename = "allowVolumeExpansion", default, skip_serializing_if = "Option::is_none")]
    pub allow_volume_expansion: Option<bool>,

    /// allowedTopologies restrict the node topologies where volumes can be dynamically provisioned. Each volume plugin defines its own supported topology specifications. An empty TopologySelectorTerm list means there is no topology restriction. This field is only honored by servers that enable the VolumeScheduling feature.
    #[serde(rename = "allowedTopologies", default, skip_serializing_if = "Option::is_none")]
    pub allowed_topologies: Option<Vec<crate::io::k8s::api::core::v1::TopologySelectorTerm>>,

    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `storage.k8s.io/v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `StorageClass`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// metadata is the standard object metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ObjectMeta>,

    /// mountOptions controls the mountOptions for dynamically provisioned PersistentVolumes of this storage class. e.g. ["ro", "soft"]. Not validated - mount of the PVs will simply fail if one is invalid.
    #[serde(rename = "mountOptions", default, skip_serializing_if = "Option::is_none")]
    pub mount_options: Option<Vec<String>>,

    /// parameters holds the parameters for the provisioner that should create volumes of this storage class.
    #[serde(rename = "parameters", default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<std::collections::BTreeMap<String, String>>,

    /// provisioner indicates the type of the provisioner.
    #[serde(rename = "provisioner", default, skip_serializing_if = "Option::is_none")]
    pub provisioner: Option<String>,

    /// reclaimPolicy controls the reclaimPolicy for dynamically provisioned PersistentVolumes of this storage class. Defaults to Delete.
    #[serde(rename = "reclaimPolicy", default, skip_serializing_if = "Option::is_none")]
    pub reclaim_policy: Option<String>,

    /// volumeBindingMode indicates how PersistentVolumeClaims should be provisioned and bound.  When unset, VolumeBindingImmediate is used. This field is only honored by servers that enable the VolumeScheduling feature.
    #[serde(rename = "volumeBindingMode", default, skip_serializing_if = "Option::is_none")]
    pub volume_binding_mode: Option<String>,
}

impl StorageClass {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "storage.k8s.io/v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "StorageClass";
}

impl Default for StorageClass {
    fn default() -> Self {
        Self {
            allow_volume_expansion: None,
            allowed_topologies: None,
            api_version: Some(Self::API_VERSION.to_string()),
            kind: Some(Self::KIND.to_string()),
            metadata: None,
            mount_options: None,
            parameters: None,
            provisioner: None,
            reclaim_policy: None,
            volume_binding_mode: None,
        }
    }
}

/// StorageClassList is a collection of storage classes.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct StorageClassList {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `storage.k8s.io/v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// items is the list of StorageClasses
    #[serde(rename = "items", default, skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::io::k8s::api::storage::v1::StorageClass>>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `StorageClassList`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard list metadata More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ListMeta>,
}

impl StorageClassList {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "storage.k8s.io/v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "StorageClassList";
}

impl Default for StorageClassList {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            items: None,
            kind: Some(Self::KIND.to_string()),
            metadata: None,
        }
    }
}
