// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// TokenRequest contains parameters of a service account token.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TokenRequest {
    /// audience is the intended audience of the token in "TokenRequestSpec". It will default to the audiences of kube apiserver.
    #[serde(rename = "audience", default, skip_serializing_if = "Option::is_none")]
    pub audience: Option<String>,

    /// expirationSeconds is the duration of validity of the token in "TokenRequestSpec". It has the same default value of "ExpirationSeconds" in "TokenRequestSpec".
    #[serde(rename = "expirationSeconds", default, skip_serializing_if = "Option::is_none")]
    pub expiration_seconds: Option<i64>,
}
