// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// VolumeAttachment captures the intent to attach or detach the specified volume to/from the specified node.
///
/// VolumeAttachment objects are non-namespaced.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct VolumeAttachment {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `storage.k8s.io/v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `VolumeAttachment`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// metadata is the standard object metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ObjectMeta>,

    /// spec represents specification of the desired attach/detach volume behavior. Populated by the Kubernetes system.
    #[serde(rename = "spec", default, skip_serializing_if = "Option::is_none")]
    pub spec: Option<crate::io::k8s::api::storage::v1::VolumeAttachmentSpec>,

    /// status represents status of the VolumeAttachment request. Populated by the entity completing the attach or detach operation, i.e. the external-attacher.
    #[serde(rename = "status", default, skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::io::k8s::api::storage::v1::VolumeAttachmentStatus>,
}

impl VolumeAttachment {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "storage.k8s.io/v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "VolumeAttachment";
}

impl Default for VolumeAttachment {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            kind: Some(Self::KIND.to_string()),
            metadata: None,
            spec: None,
            status: None,
        }
    }
}

/// VolumeAttachmentList is a collection of VolumeAttachment objects.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct VolumeAttachmentList {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `storage.k8s.io/v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// items is the list of VolumeAttachments
    #[serde(rename = "items", default, skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::io::k8s::api::storage::v1::VolumeAttachment>>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `VolumeAttachmentList`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard list metadata More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ListMeta>,
}

impl VolumeAttachmentList {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "storage.k8s.io/v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "VolumeAttachmentList";
}

impl Default for VolumeAttachmentList {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            items: None,
            kind: Some(Self::KIND.to_string()),
            metadata: None,
        }
    }
}

/// VolumeAttachmentSource represents a volume that should be attached. Right now only PersistentVolumes can be attached via external attacher, in the future we may allow also inline volumes in pods. Exactly one member can be set.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct VolumeAttachmentSource {
    /// inlineVolumeSpec contains all the information necessary to attach a persistent volume defined by a pod's inline VolumeSource. This field is populated only for the CSIMigration feature. It contains translated fields from a pod's inline VolumeSource to a PersistentVolumeSpec. This field is beta-level and is only honored by servers that enabled the CSIMigration feature.
    #[serde(rename = "inlineVolumeSpec", default, skip_serializing_if = "Option::is_none")]
    pub inline_volume_spec: Option<crate::io::k8s::api::core::v1::PersistentVolumeSpec>,

    /// persistentVolumeName represents the name of the persistent volume to attach.
    #[serde(rename = "persistentVolumeName", default, skip_serializing_if = "Option::is_none")]
    pub persistent_volume_name: Option<String>,
}

/// VolumeAttachmentSpec is the specification of a VolumeAttachment request.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct VolumeAttachmentSpec {
    /// attacher indicates the name of the volume driver that MUST handle this request. This is the name returned by GetPluginName().
    #[serde(rename = "attacher", default, skip_serializing_if = "Option::is_none")]
    pub attacher: Option<String>,

    /// nodeName represents the node that the volume should be attached to.
    #[serde(rename = "nodeName", default, skip_serializing_if = "Option::is_none")]
    pub node_name: Option<String>,

    /// source represents the volume that should be attached.
    #[serde(rename = "source", default, skip_serializing_if = "Option::is_none")]
    pub source: Option<crate::io::k8s::api::storage::v1::VolumeAttachmentSource>,
}

/// VolumeAttachmentStatus is the status of a VolumeAttachment request.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct VolumeAttachmentStatus {
    /// attachError represents the last error encountered during attach operation, if any. This field must only be set by the entity completing the attach operation, i.e. the external-attacher.
    #[serde(rename = "attachError", default, skip_serializing_if = "Option::is_none")]
    pub attach_error: Option<crate::io::k8s::api::storage::v1::VolumeError>,

    /// attached indicates the volume is successfully attached. This field must only be set by the entity completing the attach operation, i.e. the external-attacher.
    #[serde(rename = "attached", default, skip_serializing_if = "Option::is_none")]
    pub attached: Option<bool>,

    /// attachmentMetadata is populated with any information returned by the attach operation, upon successful attach, that must be passed into subsequent WaitForAttach or Mount calls. This field must only be set by the entity completing the attach operation, i.e. the external-attacher.
    #[serde(rename = "attachmentMetadata", default, skip_serializing_if = "Option::is_none")]
    pub attachment_metadata: Option<std::collections::BTreeMap<String, String>>,

    /// detachError represents the last error encountered during detach operation, if any. This field must only be set by the entity completing the detach operation, i.e. the external-attacher.
    #[serde(rename = "detachError", default, skip_serializing_if = "Option::is_none")]
    pub detach_error: Option<crate::io::k8s::api::storage::v1::VolumeError>,
}
