// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// WorkloadPodGroupBasicSchedulingPolicy indicates standard Kubernetes scheduling behavior.
pub type WorkloadPodGroupBasicSchedulingPolicy = serde_json::Value;
