// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// WorkloadPodGroupAllDisruptionMode indicates that all pods in the group must be disrupted together.
pub type WorkloadPodGroupAllDisruptionMode = serde_json::Value;
