// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// WorkloadPodGroupResourceClaim references a dynamic resource claim that is shared across pods in the group.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WorkloadPodGroupResourceClaim {
    /// name uniquely identifies this resource claim inside the group. This field is required. It must be a DNS_LABEL.
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// resourceClaimName is the name of a ResourceClaim object in the same namespace. This field is optional. If it is not specified, no resource claim is used. If set, it must be a DNS subdomain.
    #[serde(rename = "resourceClaimName", default, skip_serializing_if = "Option::is_none")]
    pub resource_claim_name: Option<String>,

    /// resourceClaimTemplateName is the name of a ResourceClaimTemplate object in the same namespace. This field is optional. If it is not specified, no resource claim template is used. If set, it must be a DNS subdomain.
    #[serde(rename = "resourceClaimTemplateName", default, skip_serializing_if = "Option::is_none")]
    pub resource_claim_template_name: Option<String>,
}
