// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// WorkloadPodGroupDisruptionMode defines how individual pods within a group can be disrupted. Exactly one mode must be set.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WorkloadPodGroupDisruptionMode {
    /// all specifies that all pods in the group must be disrupted together.
    #[serde(rename = "all", default, skip_serializing_if = "Option::is_none")]
    pub all: Option<crate::io::k8s::api::scheduling::v1alpha3::WorkloadPodGroupAllDisruptionMode>,

    /// single specifies that pods can be disrupted independently from each other.
    #[serde(rename = "single", default, skip_serializing_if = "Option::is_none")]
    pub single: Option<crate::io::k8s::api::scheduling::v1alpha3::WorkloadPodGroupSingleDisruptionMode>,
}
