// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// WorkloadPodGroupSingleDisruptionMode indicates that individual pods can be disrupted independently.
pub type WorkloadPodGroupSingleDisruptionMode = serde_json::Value;
