// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// WorkloadPodGroupSchedulingPolicy defines the scheduling policy for a group of pods managed by a workload controller. Exactly one policy must be set.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WorkloadPodGroupSchedulingPolicy {
    /// basic specifies that standard, pod-by-pod Kubernetes scheduling behavior should be used.
    #[serde(rename = "basic", default, skip_serializing_if = "Option::is_none")]
    pub basic: Option<crate::io::k8s::api::scheduling::v1alpha3::WorkloadPodGroupBasicSchedulingPolicy>,

    /// gang specifies all-or-nothing scheduling semantics.
    #[serde(rename = "gang", default, skip_serializing_if = "Option::is_none")]
    pub gang: Option<crate::io::k8s::api::scheduling::v1alpha3::WorkloadPodGroupGangSchedulingPolicy>,
}
