// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// WorkloadPodGroupSchedulingConstraints defines leaf-level scheduling constraints, such as topology.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WorkloadPodGroupSchedulingConstraints {
    /// topology specifies desired topological placements for all pods within the pod group. If unset, no topology placement is requested.
    #[serde(rename = "topology", default, skip_serializing_if = "Option::is_none")]
    pub topology: Option<Vec<crate::io::k8s::api::scheduling::v1alpha3::TopologyConstraint>>,
}
