// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// Input is used to provide inputs to this Function.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Input {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `autoready.fn.crossplane.io/v1beta1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// CELHealthCheckCustomization is a inline map of CEL health check customizations
    /// Inline customizations are merged with from Context customizations
    /// and take precedence over Context-provided healthchecks allowing for granular overwrites
    #[serde(rename = "celHealthCheckCustomization", default, skip_serializing_if = "Option::is_none")]
    pub cel_health_check_customization: Option<std::collections::BTreeMap<String, String>>,

    /// CELHealthCheckCustomizationFrom is a reference to fetch CEL health check customizations from context
    #[serde(rename = "celHealthCheckCustomizationFrom", default, skip_serializing_if = "Option::is_none")]
    pub cel_health_check_customization_from: Option<String>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `Input`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ObjectMeta>,

    /// TTL for which a response can be cached in time.Duration format
    #[serde(rename = "ttl", default, skip_serializing_if = "Option::is_none")]
    pub ttl: Option<String>,
}

impl Input {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "autoready.fn.crossplane.io/v1beta1";

    /// The kind of this resource.
    pub const KIND: &'static str = "Input";
}

impl Default for Input {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            cel_health_check_customization: None,
            cel_health_check_customization_from: None,
            kind: Some(Self::KIND.to_string()),
            metadata: None,
            ttl: None,
        }
    }
}

/// InputList is a list of Input
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InputList {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// List of inputs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    #[serde(rename = "items", default, skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::io::crossplane::fn_::autoready::v1beta1::Input>>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ListMeta>,
}
