apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: webapps.platform.example.com
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: WebApp
  mode: Pipeline
  pipeline:
  - functionRef:
      name: jonasz-lasut-xp-rust-democompose-webapp
    step: compose-webapp
  - functionRef:
      name: jonasz-lasut-function-wasm
    input:
      apiVersion: wasm.fn.crossplane.io/v1beta1
      kind: Input
      module:
        type: Path
        from: spec.extensionName
        allowEmpty: true
    step: extend-webapp
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
