// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// TokenRequest requests a token for a given service account.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TokenRequest {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `authentication.k8s.io/v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `TokenRequest`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// metadata is the standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ObjectMeta>,

    /// spec holds information about the request being evaluated
    #[serde(rename = "spec", default, skip_serializing_if = "Option::is_none")]
    pub spec: Option<crate::io::k8s::api::authentication::v1::TokenRequestSpec>,

    /// status is filled in by the server and indicates whether the token can be authenticated.
    #[serde(rename = "status", default, skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::io::k8s::api::authentication::v1::TokenRequestStatus>,
}

impl TokenRequest {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "authentication.k8s.io/v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "TokenRequest";
}

impl Default for TokenRequest {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            kind: Some(Self::KIND.to_string()),
            metadata: None,
            spec: None,
            status: None,
        }
    }
}

/// TokenRequestSpec contains client provided parameters of a token request.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TokenRequestSpec {
    /// attestations is a map of well-known keys to string-slice values. The values for each key have a specific semantic meaning, which is documented on the key definition. Requesters of tokens may ask the Kubernetes API Server to attest to certain claims. The API Server may perform authorization checks depending on the key of this map.
    #[serde(rename = "attestations", default, skip_serializing_if = "Option::is_none")]
    pub attestations: Option<std::collections::BTreeMap<String, Vec<String>>>,

    /// audiences are the intendend audiences of the token. A recipient of a token must identify themself with an identifier in the list of audiences of the token, and otherwise should reject the token. A token issued for multiple audiences may be used to authenticate against any of the audiences listed but implies a high degree of trust between the target audiences.
    #[serde(rename = "audiences", default, skip_serializing_if = "Option::is_none")]
    pub audiences: Option<Vec<String>>,

    /// boundObjectRef is a reference to an object that the token will be bound to. The token will only be valid for as long as the bound object exists. NOTE: The API server's TokenReview endpoint will validate the BoundObjectRef, but other audiences may not. Keep ExpirationSeconds small if you want prompt revocation.
    #[serde(rename = "boundObjectRef", default, skip_serializing_if = "Option::is_none")]
    pub bound_object_ref: Option<crate::io::k8s::api::authentication::v1::BoundObjectReference>,

    /// expirationSeconds is the requested duration of validity of the request. The token issuer may return a token with a different validity duration so a client needs to check the 'expiration' field in a response.
    #[serde(rename = "expirationSeconds", default, skip_serializing_if = "Option::is_none")]
    pub expiration_seconds: Option<i64>,
}

/// TokenRequestStatus is the result of a token request.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TokenRequestStatus {
    /// expirationTimestamp is the time of expiration of the returned token.
    #[serde(rename = "expirationTimestamp", default, skip_serializing_if = "Option::is_none")]
    pub expiration_timestamp: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::Time>,

    /// token is the opaque bearer token.
    #[serde(rename = "token", default, skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}
