// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// PodFailurePolicyRule describes how a pod failure is handled when the requirements are met. One of onExitCodes and onPodConditions, but not both, can be used in each rule.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PodFailurePolicyRule {
    /// Specifies the action taken on a pod failure when the requirements are satisfied. Possible values are:
    ///
    /// - FailJob: indicates that the pod's job is marked as Failed and all
    ///   running pods are terminated.
    /// - FailIndex: indicates that the pod's index is marked as Failed and will
    ///   not be restarted.
    /// - Ignore: indicates that the counter towards the .backoffLimit is not
    ///   incremented and a replacement pod is created.
    /// - Count: indicates that the pod is handled in the default way - the
    ///   counter towards the .backoffLimit is incremented.
    /// Additional values are considered to be added in the future. Clients should react to an unknown action by skipping the rule.
    #[serde(rename = "action", default, skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,

    /// Represents the requirement on the container exit codes.
    #[serde(rename = "onExitCodes", default, skip_serializing_if = "Option::is_none")]
    pub on_exit_codes: Option<crate::io::k8s::api::batch::v1::PodFailurePolicyOnExitCodesRequirement>,

    /// Represents the requirement on the pod conditions. The requirement is represented as a list of pod condition patterns. The requirement is satisfied if at least one pattern matches an actual pod condition. At most 20 elements are allowed.
    #[serde(rename = "onPodConditions", default, skip_serializing_if = "Option::is_none")]
    pub on_pod_conditions: Option<Vec<crate::io::k8s::api::batch::v1::PodFailurePolicyOnPodConditionsPattern>>,
}
