// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// SuccessPolicy describes when a Job can be declared as succeeded based on the success of some indexes.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SuccessPolicy {
    /// rules represents the list of alternative rules for the declaring the Jobs as successful before `.status.succeeded >= .spec.completions`. Once any of the rules are met, the "SuccessCriteriaMet" condition is added, and the lingering pods are removed. The terminal state for such a Job has the "Complete" condition. Additionally, these rules are evaluated in order; Once the Job meets one of the rules, other rules are ignored. At most 20 elements are allowed.
    #[serde(rename = "rules", default, skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<crate::io::k8s::api::batch::v1::SuccessPolicyRule>>,
}
