// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// UncountedTerminatedPods holds UIDs of Pods that have terminated but haven't been accounted in Job status counters.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UncountedTerminatedPods {
    /// failed holds UIDs of failed Pods.
    #[serde(rename = "failed", default, skip_serializing_if = "Option::is_none")]
    pub failed: Option<Vec<String>>,

    /// succeeded holds UIDs of succeeded Pods.
    #[serde(rename = "succeeded", default, skip_serializing_if = "Option::is_none")]
    pub succeeded: Option<Vec<String>>,
}
