// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// AppArmorProfile defines a pod or container's AppArmor settings.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppArmorProfile {
    /// localhostProfile indicates a profile loaded on the node that should be used. The profile must be preconfigured on the node to work. Must match the loaded name of the profile. Must be set if and only if type is "Localhost".
    #[serde(rename = "localhostProfile", default, skip_serializing_if = "Option::is_none")]
    pub localhost_profile: Option<String>,

    /// type indicates which kind of AppArmor profile will be applied. Valid options are:
    ///   Localhost - a profile pre-loaded on the node.
    ///   RuntimeDefault - the container runtime's default profile.
    ///   Unconfined - no AppArmor enforcement.
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}
