// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// Adds and removes POSIX capabilities from running containers.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Capabilities {
    /// Added capabilities
    #[serde(rename = "add", default, skip_serializing_if = "Option::is_none")]
    pub add: Option<Vec<String>>,

    /// Removed capabilities
    #[serde(rename = "drop", default, skip_serializing_if = "Option::is_none")]
    pub drop: Option<Vec<String>>,
}
