// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ComponentStatus (and ComponentStatusList) holds the cluster validation info. Deprecated: This API is deprecated in v1.19+
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ComponentStatus {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// List of component conditions observed
    #[serde(rename = "conditions", default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::io::k8s::api::core::v1::ComponentCondition>>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `ComponentStatus`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ObjectMeta>,
}

impl ComponentStatus {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "ComponentStatus";
}

impl Default for ComponentStatus {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            conditions: None,
            kind: Some(Self::KIND.to_string()),
            metadata: None,
        }
    }
}

/// Status of all the conditions for the component as a list of ComponentStatus objects. Deprecated: This API is deprecated in v1.19+
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ComponentStatusList {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// List of ComponentStatus objects.
    #[serde(rename = "items", default, skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::io::k8s::api::core::v1::ComponentStatus>>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `ComponentStatusList`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ListMeta>,
}

impl ComponentStatusList {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "ComponentStatusList";
}

impl Default for ComponentStatusList {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            items: None,
            kind: Some(Self::KIND.to_string()),
            metadata: None,
        }
    }
}
