// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ContainerStateTerminated is a terminated state of a container.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ContainerStateTerminated {
    /// Container's ID in the format '<type>://<container_id>'
    #[serde(rename = "containerID", default, skip_serializing_if = "Option::is_none")]
    pub container_id: Option<String>,

    /// Exit status from the last termination of the container
    #[serde(rename = "exitCode", default, skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,

    /// Time at which the container last terminated
    #[serde(rename = "finishedAt", default, skip_serializing_if = "Option::is_none")]
    pub finished_at: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::Time>,

    /// Message regarding the last termination of the container
    #[serde(rename = "message", default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,

    /// (brief) reason from the last termination of the container
    #[serde(rename = "reason", default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,

    /// Signal from the last termination of the container
    #[serde(rename = "signal", default, skip_serializing_if = "Option::is_none")]
    pub signal: Option<i32>,

    /// Time at which previous execution of the container started
    #[serde(rename = "startedAt", default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::Time>,
}
