// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ContainerRestartRule describes how a container exit is handled.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ContainerRestartRule {
    /// Specifies the action taken on a container exit if the requirements are satisfied. The only possible value is "Restart" to restart the container.
    #[serde(rename = "action", default, skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,

    /// Represents the exit codes to check on container exits.
    #[serde(rename = "exitCodes", default, skip_serializing_if = "Option::is_none")]
    pub exit_codes: Option<crate::io::k8s::api::core::v1::ContainerRestartRuleOnExitCodes>,
}
