// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ContainerExtendedResourceRequest has the mapping of container name, extended resource name to the device request name.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ContainerExtendedResourceRequest {
    /// The name of the container requesting resources.
    #[serde(rename = "containerName", default, skip_serializing_if = "Option::is_none")]
    pub container_name: Option<String>,

    /// The name of the request in the special ResourceClaim which corresponds to the extended resource.
    #[serde(rename = "requestName", default, skip_serializing_if = "Option::is_none")]
    pub request_name: Option<String>,

    /// The name of the extended resource in that container which gets backed by DRA.
    #[serde(rename = "resourceName", default, skip_serializing_if = "Option::is_none")]
    pub resource_name: Option<String>,
}
