// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// Describe a container image
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ContainerImage {
    /// Names by which this image is known. e.g. ["kubernetes.example/hyperkube:v1.0.7", "cloud-vendor.registry.example/cloud-vendor/hyperkube:v1.0.7"]
    #[serde(rename = "names", default, skip_serializing_if = "Option::is_none")]
    pub names: Option<Vec<String>>,

    /// The size of the image in bytes.
    #[serde(rename = "sizeBytes", default, skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<i64>,
}
