// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ContainerRestartRuleOnExitCodes describes the condition for handling an exited container based on its exit codes.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ContainerRestartRuleOnExitCodes {
    /// Represents the relationship between the container exit code(s) and the specified values. Possible values are: - In: the requirement is satisfied if the container exit code is in the
    ///   set of specified values.
    /// - NotIn: the requirement is satisfied if the container exit code is
    ///   not in the set of specified values.
    #[serde(rename = "operator", default, skip_serializing_if = "Option::is_none")]
    pub operator: Option<String>,

    /// Specifies the set of values to check for container exit codes. At most 255 elements are allowed.
    #[serde(rename = "values", default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<i32>>,
}
