// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ContainerUser represents user identity information
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ContainerUser {
    /// Linux holds user identity information initially attached to the first process of the containers in Linux. Note that the actual running identity can be changed if the process has enough privilege to do so.
    #[serde(rename = "linux", default, skip_serializing_if = "Option::is_none")]
    pub linux: Option<crate::io::k8s::api::core::v1::LinuxContainerUser>,
}
