// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ContainerStatus contains details for the current status of this container.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ContainerStatus {
    /// AllocatedResources represents the compute resources allocated for this container by the node. Kubelet sets this value to Container.Resources.Requests upon successful pod admission and after successfully admitting desired pod resize.
    #[serde(rename = "allocatedResources", default, skip_serializing_if = "Option::is_none")]
    pub allocated_resources: Option<std::collections::BTreeMap<String, crate::io::k8s::apimachinery::pkg::api::resource::Quantity>>,

    /// AllocatedResourcesStatus represents the status of various resources allocated for this Pod.
    #[serde(rename = "allocatedResourcesStatus", default, skip_serializing_if = "Option::is_none")]
    pub allocated_resources_status: Option<Vec<crate::io::k8s::api::core::v1::ResourceStatus>>,

    /// ContainerID is the ID of the container in the format '<type>://<container_id>'. Where type is a container runtime identifier, returned from Version call of CRI API (for example "containerd").
    #[serde(rename = "containerID", default, skip_serializing_if = "Option::is_none")]
    pub container_id: Option<String>,

    /// Image is the name of container image that the container is running. The container image may not match the image used in the PodSpec, as it may have been resolved by the runtime. More info: https://kubernetes.io/docs/concepts/containers/images.
    #[serde(rename = "image", default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,

    /// ImageID is the image ID of the container's image. The image ID may not match the image ID of the image used in the PodSpec, as it may have been resolved by the runtime.
    #[serde(rename = "imageID", default, skip_serializing_if = "Option::is_none")]
    pub image_id: Option<String>,

    /// LastTerminationState holds the last termination state of the container to help debug container crashes and restarts. This field is not populated if the container is still running and RestartCount is 0.
    #[serde(rename = "lastState", default, skip_serializing_if = "Option::is_none")]
    pub last_state: Option<crate::io::k8s::api::core::v1::ContainerState>,

    /// Name is a DNS_LABEL representing the unique name of the container. Each container in a pod must have a unique name across all container types. Cannot be updated.
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Ready specifies whether the container is currently passing its readiness check. The value will change as readiness probes keep executing. If no readiness probes are specified, this field defaults to true once the container is fully started (see Started field).
    ///
    /// The value is typically used to determine whether a container is ready to accept traffic.
    #[serde(rename = "ready", default, skip_serializing_if = "Option::is_none")]
    pub ready: Option<bool>,

    /// Resources represents the compute resource requests and limits that have been successfully enacted on the running container after it has been started or has been successfully resized.
    #[serde(rename = "resources", default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<crate::io::k8s::api::core::v1::ResourceRequirements>,

    /// RestartCount holds the number of times the container has been restarted. Kubelet makes an effort to always increment the value, but there are cases when the state may be lost due to node restarts and then the value may be reset to 0. The value is never negative.
    #[serde(rename = "restartCount", default, skip_serializing_if = "Option::is_none")]
    pub restart_count: Option<i32>,

    /// Started indicates whether the container has finished its postStart lifecycle hook and passed its startup probe. Initialized as false, becomes true after startupProbe is considered successful. Resets to false when the container is restarted, or if kubelet loses state temporarily. In both cases, startup probes will run again. Is always true when no startupProbe is defined and container is running and has passed the postStart lifecycle hook. The null value must be treated the same as false.
    #[serde(rename = "started", default, skip_serializing_if = "Option::is_none")]
    pub started: Option<bool>,

    /// State holds details about the container's current condition.
    #[serde(rename = "state", default, skip_serializing_if = "Option::is_none")]
    pub state: Option<crate::io::k8s::api::core::v1::ContainerState>,

    /// StopSignal reports the effective stop signal for this container
    #[serde(rename = "stopSignal", default, skip_serializing_if = "Option::is_none")]
    pub stop_signal: Option<String>,

    /// User represents user identity information initially attached to the first process of the container
    #[serde(rename = "user", default, skip_serializing_if = "Option::is_none")]
    pub user: Option<crate::io::k8s::api::core::v1::ContainerUser>,

    /// Status of volume mounts.
    #[serde(rename = "volumeMounts", default, skip_serializing_if = "Option::is_none")]
    pub volume_mounts: Option<Vec<crate::io::k8s::api::core::v1::VolumeMountStatus>>,
}
