// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ContainerResizePolicy represents resource resize policy for the container.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ContainerResizePolicy {
    /// Name of the resource to which this resource resize policy applies. Supported values: cpu, memory.
    #[serde(rename = "resourceName", default, skip_serializing_if = "Option::is_none")]
    pub resource_name: Option<String>,

    /// Restart policy to apply when specified resource is resized. If not specified, it defaults to NotRequired.
    #[serde(rename = "restartPolicy", default, skip_serializing_if = "Option::is_none")]
    pub restart_policy: Option<String>,
}
