// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ContainerState holds a possible state of container. Only one of its members may be specified. If none of them is specified, the default one is ContainerStateWaiting.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ContainerState {
    /// Details about a running container
    #[serde(rename = "running", default, skip_serializing_if = "Option::is_none")]
    pub running: Option<crate::io::k8s::api::core::v1::ContainerStateRunning>,

    /// Details about a terminated container
    #[serde(rename = "terminated", default, skip_serializing_if = "Option::is_none")]
    pub terminated: Option<crate::io::k8s::api::core::v1::ContainerStateTerminated>,

    /// Details about a waiting container
    #[serde(rename = "waiting", default, skip_serializing_if = "Option::is_none")]
    pub waiting: Option<crate::io::k8s::api::core::v1::ContainerStateWaiting>,
}
