// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// Represents storage that is managed by an external CSI volume driver
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CSIPersistentVolumeSource {
    /// controllerExpandSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI ControllerExpandVolume call. This field is optional, and may be empty if no secret is required. If the secret object contains more than one secret, all secrets are passed.
    #[serde(rename = "controllerExpandSecretRef", default, skip_serializing_if = "Option::is_none")]
    pub controller_expand_secret_ref: Option<crate::io::k8s::api::core::v1::SecretReference>,

    /// controllerPublishSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI ControllerPublishVolume and ControllerUnpublishVolume calls. This field is optional, and may be empty if no secret is required. If the secret object contains more than one secret, all secrets are passed.
    #[serde(rename = "controllerPublishSecretRef", default, skip_serializing_if = "Option::is_none")]
    pub controller_publish_secret_ref: Option<crate::io::k8s::api::core::v1::SecretReference>,

    /// driver is the name of the driver to use for this volume. Required.
    #[serde(rename = "driver", default, skip_serializing_if = "Option::is_none")]
    pub driver: Option<String>,

    /// fsType to mount. Must be a filesystem type supported by the host operating system. Ex. "ext4", "xfs", "ntfs".
    #[serde(rename = "fsType", default, skip_serializing_if = "Option::is_none")]
    pub fs_type: Option<String>,

    /// nodeExpandSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI NodeExpandVolume call. This field is optional, may be omitted if no secret is required. If the secret object contains more than one secret, all secrets are passed.
    #[serde(rename = "nodeExpandSecretRef", default, skip_serializing_if = "Option::is_none")]
    pub node_expand_secret_ref: Option<crate::io::k8s::api::core::v1::SecretReference>,

    /// nodePublishSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI NodePublishVolume and NodeUnpublishVolume calls. This field is optional, and may be empty if no secret is required. If the secret object contains more than one secret, all secrets are passed.
    #[serde(rename = "nodePublishSecretRef", default, skip_serializing_if = "Option::is_none")]
    pub node_publish_secret_ref: Option<crate::io::k8s::api::core::v1::SecretReference>,

    /// nodeStageSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI NodeStageVolume and NodeStageVolume and NodeUnstageVolume calls. This field is optional, and may be empty if no secret is required. If the secret object contains more than one secret, all secrets are passed.
    #[serde(rename = "nodeStageSecretRef", default, skip_serializing_if = "Option::is_none")]
    pub node_stage_secret_ref: Option<crate::io::k8s::api::core::v1::SecretReference>,

    /// readOnly value to pass to ControllerPublishVolumeRequest. Defaults to false (read/write).
    #[serde(rename = "readOnly", default, skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,

    /// volumeAttributes of the volume to publish.
    #[serde(rename = "volumeAttributes", default, skip_serializing_if = "Option::is_none")]
    pub volume_attributes: Option<std::collections::BTreeMap<String, String>>,

    /// volumeHandle is the unique volume name returned by the CSI volume plugin’s CreateVolume to refer to the volume on all subsequent calls. Required.
    #[serde(rename = "volumeHandle", default, skip_serializing_if = "Option::is_none")]
    pub volume_handle: Option<String>,
}
