// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// DaemonEndpoint contains information about a single Daemon endpoint.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DaemonEndpoint {
    /// Port number of the given endpoint.
    #[serde(rename = "Port", default, skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
}
