// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// Endpoints is a collection of endpoints that implement the actual service. Example:
///
/// 	 Name: "mysvc",
/// 	 Subsets: [
/// 	   {
/// 	     Addresses: [{"ip": "10.10.1.1"}, {"ip": "10.10.2.2"}],
/// 	     Ports: [{"name": "a", "port": 8675}, {"name": "b", "port": 309}]
/// 	   },
/// 	   {
/// 	     Addresses: [{"ip": "10.10.3.3"}],
/// 	     Ports: [{"name": "a", "port": 93}, {"name": "b", "port": 76}]
/// 	   },
/// 	]
///
/// Endpoints is a legacy API and does not contain information about all Service features. Use discoveryv1.EndpointSlice for complete information about Service endpoints.
///
/// Deprecated: This API is deprecated in v1.33+. Use discoveryv1.EndpointSlice.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Endpoints {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `Endpoints`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ObjectMeta>,

    /// The set of all endpoints is the union of all subsets. Addresses are placed into subsets according to the IPs they share. A single address with multiple ports, some of which are ready and some of which are not (because they come from different containers) will result in the address being displayed in different subsets for the different ports. No address will appear in both Addresses and NotReadyAddresses in the same subset. Sets of addresses and ports that comprise a service.
    #[serde(rename = "subsets", default, skip_serializing_if = "Option::is_none")]
    pub subsets: Option<Vec<crate::io::k8s::api::core::v1::EndpointSubset>>,
}

impl Endpoints {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "Endpoints";
}

impl Default for Endpoints {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            kind: Some(Self::KIND.to_string()),
            metadata: None,
            subsets: None,
        }
    }
}

/// EndpointsList is a list of endpoints. Deprecated: This API is deprecated in v1.33+.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EndpointsList {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// List of endpoints.
    #[serde(rename = "items", default, skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::io::k8s::api::core::v1::Endpoints>>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `EndpointsList`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ListMeta>,
}

impl EndpointsList {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "EndpointsList";
}

impl Default for EndpointsList {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            items: None,
            kind: Some(Self::KIND.to_string()),
            metadata: None,
        }
    }
}
