// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// EndpointAddress is a tuple that describes single IP address. Deprecated: This API is deprecated in v1.33+.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EndpointAddress {
    /// The Hostname of this endpoint
    #[serde(rename = "hostname", default, skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,

    /// The IP of this endpoint. May not be loopback (127.0.0.0/8 or ::1), link-local (169.254.0.0/16 or fe80::/10), or link-local multicast (224.0.0.0/24 or ff02::/16).
    #[serde(rename = "ip", default, skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,

    /// Optional: Node hosting this endpoint. This can be used to determine endpoints local to a node.
    #[serde(rename = "nodeName", default, skip_serializing_if = "Option::is_none")]
    pub node_name: Option<String>,

    /// Reference to object providing the endpoint.
    #[serde(rename = "targetRef", default, skip_serializing_if = "Option::is_none")]
    pub target_ref: Option<crate::io::k8s::api::core::v1::ObjectReference>,
}
