// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// EnvFromSource represents the source of a set of ConfigMaps or Secrets
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EnvFromSource {
    /// The ConfigMap to select from
    #[serde(rename = "configMapRef", default, skip_serializing_if = "Option::is_none")]
    pub config_map_ref: Option<crate::io::k8s::api::core::v1::ConfigMapEnvSource>,

    /// Optional text to prepend to the name of each environment variable. May consist of any printable ASCII characters except '='.
    #[serde(rename = "prefix", default, skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,

    /// The Secret to select from
    #[serde(rename = "secretRef", default, skip_serializing_if = "Option::is_none")]
    pub secret_ref: Option<crate::io::k8s::api::core::v1::SecretEnvSource>,
}
