// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// EnvVarSource represents a source for the value of an EnvVar.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EnvVarSource {
    /// Selects a key of a ConfigMap.
    #[serde(rename = "configMapKeyRef", default, skip_serializing_if = "Option::is_none")]
    pub config_map_key_ref: Option<crate::io::k8s::api::core::v1::ConfigMapKeySelector>,

    /// Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.
    #[serde(rename = "fieldRef", default, skip_serializing_if = "Option::is_none")]
    pub field_ref: Option<crate::io::k8s::api::core::v1::ObjectFieldSelector>,

    /// FileKeyRef selects a key of the env file. Requires the EnvFiles feature gate to be enabled.
    #[serde(rename = "fileKeyRef", default, skip_serializing_if = "Option::is_none")]
    pub file_key_ref: Option<crate::io::k8s::api::core::v1::FileKeySelector>,

    /// Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.
    #[serde(rename = "resourceFieldRef", default, skip_serializing_if = "Option::is_none")]
    pub resource_field_ref: Option<crate::io::k8s::api::core::v1::ResourceFieldSelector>,

    /// Selects a key of a secret in the pod's namespace
    #[serde(rename = "secretKeyRef", default, skip_serializing_if = "Option::is_none")]
    pub secret_key_ref: Option<crate::io::k8s::api::core::v1::SecretKeySelector>,
}
