// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// EnvVar represents an environment variable present in a Container.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EnvVar {
    /// Name of the environment variable. May consist of any printable ASCII characters except '='.
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Variable references $(VAR_NAME) are expanded using the previously defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to "".
    #[serde(rename = "value", default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,

    /// Source for the environment variable's value. Cannot be used if value is not empty.
    #[serde(rename = "valueFrom", default, skip_serializing_if = "Option::is_none")]
    pub value_from: Option<crate::io::k8s::api::core::v1::EnvVarSource>,
}
