// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// An EphemeralContainer is a temporary container that you may add to an existing Pod for user-initiated activities such as debugging. Ephemeral containers have no resource or scheduling guarantees, and they will not be restarted when they exit or when a Pod is removed or restarted. The kubelet may evict a Pod if an ephemeral container causes the Pod to exceed its resource allocation.
///
/// To add an ephemeral container, use the ephemeralcontainers subresource of an existing Pod. Ephemeral containers may not be removed or restarted.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EphemeralContainer {
    /// Arguments to the entrypoint. The image's CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
    #[serde(rename = "args", default, skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<String>>,

    /// Entrypoint array. Not executed within a shell. The image's ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
    #[serde(rename = "command", default, skip_serializing_if = "Option::is_none")]
    pub command: Option<Vec<String>>,

    /// List of environment variables to set in the container. Cannot be updated.
    #[serde(rename = "env", default, skip_serializing_if = "Option::is_none")]
    pub env: Option<Vec<crate::io::k8s::api::core::v1::EnvVar>>,

    /// List of sources to populate environment variables in the container. The keys defined within a source may consist of any printable ASCII characters except '='. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated.
    #[serde(rename = "envFrom", default, skip_serializing_if = "Option::is_none")]
    pub env_from: Option<Vec<crate::io::k8s::api::core::v1::EnvFromSource>>,

    /// Container image name. More info: https://kubernetes.io/docs/concepts/containers/images
    #[serde(rename = "image", default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,

    /// Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images
    #[serde(rename = "imagePullPolicy", default, skip_serializing_if = "Option::is_none")]
    pub image_pull_policy: Option<String>,

    /// Lifecycle is not allowed for ephemeral containers.
    #[serde(rename = "lifecycle", default, skip_serializing_if = "Option::is_none")]
    pub lifecycle: Option<crate::io::k8s::api::core::v1::Lifecycle>,

    /// Probes are not allowed for ephemeral containers.
    #[serde(rename = "livenessProbe", default, skip_serializing_if = "Option::is_none")]
    pub liveness_probe: Option<crate::io::k8s::api::core::v1::Probe>,

    /// Name of the ephemeral container specified as a DNS_LABEL. This name must be unique among all containers, init containers and ephemeral containers.
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Ports are not allowed for ephemeral containers.
    #[serde(rename = "ports", default, skip_serializing_if = "Option::is_none")]
    pub ports: Option<Vec<crate::io::k8s::api::core::v1::ContainerPort>>,

    /// Probes are not allowed for ephemeral containers.
    #[serde(rename = "readinessProbe", default, skip_serializing_if = "Option::is_none")]
    pub readiness_probe: Option<crate::io::k8s::api::core::v1::Probe>,

    /// Resources resize policy for the container.
    #[serde(rename = "resizePolicy", default, skip_serializing_if = "Option::is_none")]
    pub resize_policy: Option<Vec<crate::io::k8s::api::core::v1::ContainerResizePolicy>>,

    /// Resources are not allowed for ephemeral containers. Ephemeral containers use spare resources already allocated to the pod.
    #[serde(rename = "resources", default, skip_serializing_if = "Option::is_none")]
    pub resources: Option<crate::io::k8s::api::core::v1::ResourceRequirements>,

    /// Restart policy for the container to manage the restart behavior of each container within a pod. You cannot set this field on ephemeral containers.
    #[serde(rename = "restartPolicy", default, skip_serializing_if = "Option::is_none")]
    pub restart_policy: Option<String>,

    /// Represents a list of rules to be checked to determine if the container should be restarted on exit. You cannot set this field on ephemeral containers.
    #[serde(rename = "restartPolicyRules", default, skip_serializing_if = "Option::is_none")]
    pub restart_policy_rules: Option<Vec<crate::io::k8s::api::core::v1::ContainerRestartRule>>,

    /// Optional: SecurityContext defines the security options the ephemeral container should be run with. If set, the fields of SecurityContext override the equivalent fields of PodSecurityContext.
    #[serde(rename = "securityContext", default, skip_serializing_if = "Option::is_none")]
    pub security_context: Option<crate::io::k8s::api::core::v1::SecurityContext>,

    /// Probes are not allowed for ephemeral containers.
    #[serde(rename = "startupProbe", default, skip_serializing_if = "Option::is_none")]
    pub startup_probe: Option<crate::io::k8s::api::core::v1::Probe>,

    /// Whether this container should allocate a buffer for stdin in the container runtime. If this is not set, reads from stdin in the container will always result in EOF. Default is false.
    #[serde(rename = "stdin", default, skip_serializing_if = "Option::is_none")]
    pub stdin: Option<bool>,

    /// Whether the container runtime should close the stdin channel after it has been opened by a single attach. When stdin is true the stdin stream will remain open across multiple attach sessions. If stdinOnce is set to true, stdin is opened on container start, is empty until the first client attaches to stdin, and then remains open and accepts data until the client disconnects, at which time stdin is closed and remains closed until the container is restarted. If this flag is false, a container processes that reads from stdin will never receive an EOF. Default is false
    #[serde(rename = "stdinOnce", default, skip_serializing_if = "Option::is_none")]
    pub stdin_once: Option<bool>,

    /// If set, the name of the container from PodSpec that this ephemeral container targets. The ephemeral container will be run in the namespaces (IPC, PID, etc) of this container. If not set then the ephemeral container uses the namespaces configured in the Pod spec.
    ///
    /// The container runtime must implement support for this feature. If the runtime does not support namespace targeting then the result of setting this field is undefined.
    #[serde(rename = "targetContainerName", default, skip_serializing_if = "Option::is_none")]
    pub target_container_name: Option<String>,

    /// Optional: Path at which the file to which the container's termination message will be written is mounted into the container's filesystem. Message written is intended to be brief final status, such as an assertion failure message. Will be truncated by the node if greater than 4096 bytes. The total message length across all containers will be limited to 12kb. Defaults to /dev/termination-log. Cannot be updated.
    #[serde(rename = "terminationMessagePath", default, skip_serializing_if = "Option::is_none")]
    pub termination_message_path: Option<String>,

    /// Indicate how the termination message should be populated. File will use the contents of terminationMessagePath to populate the container status message on both success and failure. FallbackToLogsOnError will use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to File. Cannot be updated.
    #[serde(rename = "terminationMessagePolicy", default, skip_serializing_if = "Option::is_none")]
    pub termination_message_policy: Option<String>,

    /// Whether this container should allocate a TTY for itself, also requires 'stdin' to be true. Default is false.
    #[serde(rename = "tty", default, skip_serializing_if = "Option::is_none")]
    pub tty: Option<bool>,

    /// volumeDevices is the list of block devices to be used by the container.
    #[serde(rename = "volumeDevices", default, skip_serializing_if = "Option::is_none")]
    pub volume_devices: Option<Vec<crate::io::k8s::api::core::v1::VolumeDevice>>,

    /// Pod volumes to mount into the container's filesystem. Subpath mounts are not allowed for ephemeral containers. Cannot be updated.
    #[serde(rename = "volumeMounts", default, skip_serializing_if = "Option::is_none")]
    pub volume_mounts: Option<Vec<crate::io::k8s::api::core::v1::VolumeMount>>,

    /// Container's working directory. If not specified, the container runtime's default will be used, which might be configured in the container image. Cannot be updated.
    #[serde(rename = "workingDir", default, skip_serializing_if = "Option::is_none")]
    pub working_dir: Option<String>,
}
