// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// Event is a report of an event somewhere in the cluster.  Events have a limited retention time and triggers and messages may evolve with time.  Event consumers should not rely on the timing of an event with a given Reason reflecting a consistent underlying trigger, or the continued existence of events with that Reason.  Events should be treated as informative, best-effort, supplemental data.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Event {
    /// What action was taken/failed regarding to the Regarding object.
    #[serde(rename = "action", default, skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,

    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// The number of times this event has occurred.
    #[serde(rename = "count", default, skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,

    /// Time when this Event was first observed.
    #[serde(rename = "eventTime", default, skip_serializing_if = "Option::is_none")]
    pub event_time: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::MicroTime>,

    /// The time at which the event was first recorded. (Time of server receipt is in TypeMeta.)
    #[serde(rename = "firstTimestamp", default, skip_serializing_if = "Option::is_none")]
    pub first_timestamp: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::Time>,

    /// The object that this event is about.
    #[serde(rename = "involvedObject", default, skip_serializing_if = "Option::is_none")]
    pub involved_object: Option<crate::io::k8s::api::core::v1::ObjectReference>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `Event`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// The time at which the most recent occurrence of this event was recorded.
    #[serde(rename = "lastTimestamp", default, skip_serializing_if = "Option::is_none")]
    pub last_timestamp: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::Time>,

    /// A human-readable description of the status of this operation.
    #[serde(rename = "message", default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,

    /// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ObjectMeta>,

    /// This should be a short, machine understandable string that gives the reason for the transition into the object's current status.
    #[serde(rename = "reason", default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,

    /// Optional secondary object for more complex actions.
    #[serde(rename = "related", default, skip_serializing_if = "Option::is_none")]
    pub related: Option<crate::io::k8s::api::core::v1::ObjectReference>,

    /// Name of the controller that emitted this Event, e.g. `kubernetes.io/kubelet`.
    #[serde(rename = "reportingComponent", default, skip_serializing_if = "Option::is_none")]
    pub reporting_component: Option<String>,

    /// ID of the controller instance, e.g. `kubelet-xyzf`.
    #[serde(rename = "reportingInstance", default, skip_serializing_if = "Option::is_none")]
    pub reporting_instance: Option<String>,

    /// Data about the Event series this event represents or nil if it's a singleton Event.
    #[serde(rename = "series", default, skip_serializing_if = "Option::is_none")]
    pub series: Option<crate::io::k8s::api::core::v1::EventSeries>,

    /// The component reporting this event. Should be a short machine understandable string.
    #[serde(rename = "source", default, skip_serializing_if = "Option::is_none")]
    pub source: Option<crate::io::k8s::api::core::v1::EventSource>,

    /// Type of this event (Normal, Warning), new types could be added in the future
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl Event {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "Event";
}

impl Default for Event {
    fn default() -> Self {
        Self {
            action: None,
            api_version: Some(Self::API_VERSION.to_string()),
            count: None,
            event_time: None,
            first_timestamp: None,
            involved_object: None,
            kind: Some(Self::KIND.to_string()),
            last_timestamp: None,
            message: None,
            metadata: None,
            reason: None,
            related: None,
            reporting_component: None,
            reporting_instance: None,
            series: None,
            source: None,
            r#type: None,
        }
    }
}

/// EventList is a list of events.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EventList {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// List of events
    #[serde(rename = "items", default, skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::io::k8s::api::core::v1::Event>>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `EventList`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ListMeta>,
}

impl EventList {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "EventList";
}

impl Default for EventList {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            items: None,
            kind: Some(Self::KIND.to_string()),
            metadata: None,
        }
    }
}

/// EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EventSeries {
    /// Number of occurrences in this series up to the last heartbeat time
    #[serde(rename = "count", default, skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,

    /// Time of the last occurrence observed
    #[serde(rename = "lastObservedTime", default, skip_serializing_if = "Option::is_none")]
    pub last_observed_time: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::MicroTime>,
}

/// EventSource contains information for an event.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EventSource {
    /// Component from which the event is generated.
    #[serde(rename = "component", default, skip_serializing_if = "Option::is_none")]
    pub component: Option<String>,

    /// Node name on which the event is generated.
    #[serde(rename = "host", default, skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
}
