// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// Represents a volume that is populated with the contents of a git repository. Git repo volumes do not support ownership management. Git repo volumes support SELinux relabeling.
///
/// DEPRECATED: GitRepo is deprecated. To provision a container with a git repo, mount an EmptyDir into an InitContainer that clones the repo using git, then mount the EmptyDir into the Pod's container.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GitRepoVolumeSource {
    /// directory is the target directory name. Must not contain or start with '..'.  If '.' is supplied, the volume directory will be the git repository.  Otherwise, if specified, the volume will contain the git repository in the subdirectory with the given name.
    #[serde(rename = "directory", default, skip_serializing_if = "Option::is_none")]
    pub directory: Option<String>,

    /// repository is the URL
    #[serde(rename = "repository", default, skip_serializing_if = "Option::is_none")]
    pub repository: Option<String>,

    /// revision is the commit hash for the specified revision.
    #[serde(rename = "revision", default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
}
