// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// GRPCAction specifies an action involving a GRPC service.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GRPCAction {
    /// mode specifies the connection mode for the gRPC health probe. Set to "TLS" to use TLS without certificate verification. Set to "Plaintext" to use a plaintext (insecure) connection explicitly. If not specified, the probe uses a plaintext (insecure) connection.
    #[serde(rename = "mode", default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,

    /// Port number of the gRPC service. Number must be in the range 1 to 65535.
    #[serde(rename = "port", default, skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,

    /// Service is the name of the service to place in the gRPC HealthCheckRequest (see https://github.com/grpc/grpc/blob/master/doc/health-checking.md).
    ///
    /// If this is not specified, the default behavior is defined by gRPC.
    #[serde(rename = "service", default, skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
}
