// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// HostAlias holds the mapping between IP and hostnames that will be injected as an entry in the pod's hosts file.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HostAlias {
    /// Hostnames for the above IP address.
    #[serde(rename = "hostnames", default, skip_serializing_if = "Option::is_none")]
    pub hostnames: Option<Vec<String>>,

    /// IP address of the host file entry.
    #[serde(rename = "ip", default, skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
}
