// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// HTTPHeader describes a custom header to be used in HTTP probes
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HTTPHeader {
    /// The header field name. This will be canonicalized upon output, so case-variant names will be understood as the same header.
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// The header field value
    #[serde(rename = "value", default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}
