// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// HTTPGetAction describes an action based on HTTP Get requests.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HTTPGetAction {
    /// Host name to connect to, defaults to the pod IP. You probably want to set "Host" in httpHeaders instead.
    #[serde(rename = "host", default, skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,

    /// Custom headers to set in the request. HTTP allows repeated headers.
    #[serde(rename = "httpHeaders", default, skip_serializing_if = "Option::is_none")]
    pub http_headers: Option<Vec<crate::io::k8s::api::core::v1::HTTPHeader>>,

    /// Path to access on the HTTP server.
    #[serde(rename = "path", default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,

    /// Name or number of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
    #[serde(rename = "port", default, skip_serializing_if = "Option::is_none")]
    pub port: Option<crate::io::k8s::apimachinery::pkg::util::intstr::IntOrString>,

    /// Protocol selects the wire protocol for the probe connection. Nil defaults to HTTP/1.1.
    #[serde(rename = "protocol", default, skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,

    /// Scheme to use for connecting to the host. Defaults to HTTP.
    #[serde(rename = "scheme", default, skip_serializing_if = "Option::is_none")]
    pub scheme: Option<String>,
}
