// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// LifecycleHandler defines a specific action that should be taken in a lifecycle hook. One and only one of the fields, except TCPSocket must be specified.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LifecycleHandler {
    /// Exec specifies a command to execute in the container.
    #[serde(rename = "exec", default, skip_serializing_if = "Option::is_none")]
    pub exec: Option<crate::io::k8s::api::core::v1::ExecAction>,

    /// HTTPGet specifies an HTTP GET request to perform.
    #[serde(rename = "httpGet", default, skip_serializing_if = "Option::is_none")]
    pub http_get: Option<crate::io::k8s::api::core::v1::HTTPGetAction>,

    /// Sleep represents a duration that the container should sleep.
    #[serde(rename = "sleep", default, skip_serializing_if = "Option::is_none")]
    pub sleep: Option<crate::io::k8s::api::core::v1::SleepAction>,

    /// Deprecated. TCPSocket is NOT supported as a LifecycleHandler and kept for backward compatibility. There is no validation of this field and lifecycle hooks will fail at runtime when it is specified.
    #[serde(rename = "tcpSocket", default, skip_serializing_if = "Option::is_none")]
    pub tcp_socket: Option<crate::io::k8s::api::core::v1::TCPSocketAction>,
}
