// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// LimitRange sets resource usage limits for each kind of resource in a Namespace.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LimitRange {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `LimitRange`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ObjectMeta>,

    /// Spec defines the limits enforced. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
    #[serde(rename = "spec", default, skip_serializing_if = "Option::is_none")]
    pub spec: Option<crate::io::k8s::api::core::v1::LimitRangeSpec>,
}

impl LimitRange {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "LimitRange";
}

impl Default for LimitRange {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            kind: Some(Self::KIND.to_string()),
            metadata: None,
            spec: None,
        }
    }
}

/// LimitRangeItem defines a min/max usage limit for any resource that matches on kind.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LimitRangeItem {
    /// Default resource requirement limit value by resource name if resource limit is omitted.
    #[serde(rename = "default", default, skip_serializing_if = "Option::is_none")]
    pub default: Option<std::collections::BTreeMap<String, crate::io::k8s::apimachinery::pkg::api::resource::Quantity>>,

    /// DefaultRequest is the default resource requirement request value by resource name if resource request is omitted.
    #[serde(rename = "defaultRequest", default, skip_serializing_if = "Option::is_none")]
    pub default_request: Option<std::collections::BTreeMap<String, crate::io::k8s::apimachinery::pkg::api::resource::Quantity>>,

    /// Max usage constraints on this kind by resource name.
    #[serde(rename = "max", default, skip_serializing_if = "Option::is_none")]
    pub max: Option<std::collections::BTreeMap<String, crate::io::k8s::apimachinery::pkg::api::resource::Quantity>>,

    /// MaxLimitRequestRatio if specified, the named resource must have a request and limit that are both non-zero where limit divided by request is less than or equal to the enumerated value; this represents the max burst for the named resource.
    #[serde(rename = "maxLimitRequestRatio", default, skip_serializing_if = "Option::is_none")]
    pub max_limit_request_ratio: Option<std::collections::BTreeMap<String, crate::io::k8s::apimachinery::pkg::api::resource::Quantity>>,

    /// Min usage constraints on this kind by resource name.
    #[serde(rename = "min", default, skip_serializing_if = "Option::is_none")]
    pub min: Option<std::collections::BTreeMap<String, crate::io::k8s::apimachinery::pkg::api::resource::Quantity>>,

    /// Type of resource that this limit applies to.
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

/// LimitRangeList is a list of LimitRange items.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LimitRangeList {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// Items is a list of LimitRange objects. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    #[serde(rename = "items", default, skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::io::k8s::api::core::v1::LimitRange>>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `LimitRangeList`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ListMeta>,
}

impl LimitRangeList {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "LimitRangeList";
}

impl Default for LimitRangeList {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            items: None,
            kind: Some(Self::KIND.to_string()),
            metadata: None,
        }
    }
}

/// LimitRangeSpec defines a min/max usage limit for resources that match on kind.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LimitRangeSpec {
    /// Limits is the list of LimitRangeItem objects that are enforced.
    #[serde(rename = "limits", default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<Vec<crate::io::k8s::api::core::v1::LimitRangeItem>>,
}
