// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// LinuxContainerUser represents user identity information in Linux containers
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LinuxContainerUser {
    /// GID is the primary gid initially attached to the first process in the container
    #[serde(rename = "gid", default, skip_serializing_if = "Option::is_none")]
    pub gid: Option<i64>,

    /// SupplementalGroups are the supplemental groups initially attached to the first process in the container
    #[serde(rename = "supplementalGroups", default, skip_serializing_if = "Option::is_none")]
    pub supplemental_groups: Option<Vec<i64>>,

    /// UID is the primary uid initially attached to the first process in the container
    #[serde(rename = "uid", default, skip_serializing_if = "Option::is_none")]
    pub uid: Option<i64>,
}
