// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// LoadBalancerStatus represents the status of a load-balancer.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoadBalancerStatus {
    /// Ingress is a list containing ingress points for the load-balancer. Traffic intended for the service should be sent to these ingress points.
    #[serde(rename = "ingress", default, skip_serializing_if = "Option::is_none")]
    pub ingress: Option<Vec<crate::io::k8s::api::core::v1::LoadBalancerIngress>>,
}
