// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// Node is a worker node in Kubernetes. Each node will have a unique identifier in the cache (i.e. in etcd).
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Node {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `Node`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ObjectMeta>,

    /// Spec defines the behavior of a node. https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
    #[serde(rename = "spec", default, skip_serializing_if = "Option::is_none")]
    pub spec: Option<crate::io::k8s::api::core::v1::NodeSpec>,

    /// Most recently observed status of the node. Populated by the system. Read-only. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
    #[serde(rename = "status", default, skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::io::k8s::api::core::v1::NodeStatus>,
}

impl Node {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "Node";
}

impl Default for Node {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            kind: Some(Self::KIND.to_string()),
            metadata: None,
            spec: None,
            status: None,
        }
    }
}

/// NodeAddress contains information for the node's address.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeAddress {
    /// The node address.
    #[serde(rename = "address", default, skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,

    /// Node address type, one of Hostname, ExternalIP or InternalIP.
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

/// Node affinity is a group of node affinity scheduling rules.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeAffinity {
    /// The scheduler will prefer to schedule pods to nodes that satisfy the affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node matches the corresponding matchExpressions; the node(s) with the highest sum are the most preferred.
    #[serde(rename = "preferredDuringSchedulingIgnoredDuringExecution", default, skip_serializing_if = "Option::is_none")]
    pub preferred_during_scheduling_ignored_during_execution: Option<Vec<crate::io::k8s::api::core::v1::PreferredSchedulingTerm>>,

    /// If the affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to an update), the system may or may not try to eventually evict the pod from its node.
    #[serde(rename = "requiredDuringSchedulingIgnoredDuringExecution", default, skip_serializing_if = "Option::is_none")]
    pub required_during_scheduling_ignored_during_execution: Option<crate::io::k8s::api::core::v1::NodeSelector>,
}

/// NodeAllocatableMappedResources describes mapped node allocatable resource allocations.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeAllocatableMappedResources {
    /// Name is the name of the resource (e.g., cpu, memory).
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Quantity is the total node allocatable resource capacity allocated for the claim. This claim's allocated devices is shared by all the containers referencing the claim. Kubelet adds this value to both requests and limits at the pod-level cgroup, and to limits at the container-level cgroup for each container referencing the claim.
    #[serde(rename = "quantity", default, skip_serializing_if = "Option::is_none")]
    pub quantity: Option<crate::io::k8s::apimachinery::pkg::api::resource::Quantity>,
}

/// NodeAllocatableOverheadResources describes auxiliary overhead resource allocations.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeAllocatableOverheadResources {
    /// Name is the name of the resource (e.g., cpu, memory).
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// PerContainer is the variable overhead quantity applied for each container referencing the claim. The container references are recorded in `nodeAllocatableResourceClaimStatuses.containers`. The total overhead quantity allocated for the claim is computed as: Quantity = PerPod + (PerContainer * NumReferences) Kubelet accounts for this overhead in cgroups: - Pod-level cgroup (requests and limits): Kubelet adds PerPod + (PerContainer * NumReferences). - Container-level cgroup (limits only): Kubelet adds PerPod + PerContainer for each referencing container. This allows any single container to access the pod-level overhead, while the parent cgroup caps the total usage to account for PerPod exactly once. At least one of PerPod or PerContainer must be specified. Specifying neither is an invalid configuration.
    #[serde(rename = "perContainer", default, skip_serializing_if = "Option::is_none")]
    pub per_container: Option<crate::io::k8s::apimachinery::pkg::api::resource::Quantity>,

    /// PerPod is the flat overhead quantity allocated per pod. Adding to each container limit allows individual containers to utilize the overhead, while the parent pod-level cgroup limit caps the total usage at the pod boundary where the overhead is accounted for exactly once. At least one of PerPod or PerContainer must be specified. Specifying neither is an invalid configuration.
    #[serde(rename = "perPod", default, skip_serializing_if = "Option::is_none")]
    pub per_pod: Option<crate::io::k8s::apimachinery::pkg::api::resource::Quantity>,
}

/// NodeAllocatableResourceClaimStatus describes the status of node allocatable resources allocated via DRA.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeAllocatableResourceClaimStatus {
    /// Containers lists the names of all containers in this pod that reference the claim.
    #[serde(rename = "containers", default, skip_serializing_if = "Option::is_none")]
    pub containers: Option<Vec<String>>,

    /// Mapping contains allocations through devices mapped in the device spec's `nodeAllocatableResources[...].mapping` field. This is used by kubelet for pod level and container-level cgroup enforcement.
    #[serde(rename = "mapping", default, skip_serializing_if = "Option::is_none")]
    pub mapping: Option<Vec<crate::io::k8s::api::core::v1::NodeAllocatableMappedResources>>,

    /// Overhead contains allocations through devices mapped in the device spec's `nodeAllocatableResources[...].overhead` field. This is used by kubelet for pod level and container-level cgroup enforcement.
    #[serde(rename = "overhead", default, skip_serializing_if = "Option::is_none")]
    pub overhead: Option<Vec<crate::io::k8s::api::core::v1::NodeAllocatableOverheadResources>>,

    /// ResourceClaimName is the resource claim referenced by the pod that resulted in this node allocatable resource allocation.
    #[serde(rename = "resourceClaimName", default, skip_serializing_if = "Option::is_none")]
    pub resource_claim_name: Option<String>,
}

/// NodeCondition contains condition information for a node.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeCondition {
    /// Last time we got an update on a given condition.
    #[serde(rename = "lastHeartbeatTime", default, skip_serializing_if = "Option::is_none")]
    pub last_heartbeat_time: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::Time>,

    /// Last time the condition transit from one status to another.
    #[serde(rename = "lastTransitionTime", default, skip_serializing_if = "Option::is_none")]
    pub last_transition_time: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::Time>,

    /// Human readable message indicating details about last transition.
    #[serde(rename = "message", default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,

    /// (brief) reason for the condition's last transition.
    #[serde(rename = "reason", default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,

    /// Status of the condition, one of True, False, Unknown.
    #[serde(rename = "status", default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,

    /// Type of node condition.
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

/// NodeConfigSource specifies a source of node configuration. Exactly one subfield (excluding metadata) must be non-nil. This API is deprecated since 1.22
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeConfigSource {
    /// ConfigMap is a reference to a Node's ConfigMap
    #[serde(rename = "configMap", default, skip_serializing_if = "Option::is_none")]
    pub config_map: Option<crate::io::k8s::api::core::v1::ConfigMapNodeConfigSource>,
}

/// NodeConfigStatus describes the status of the config assigned by Node.Spec.ConfigSource.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeConfigStatus {
    /// Active reports the checkpointed config the node is actively using. Active will represent either the current version of the Assigned config, or the current LastKnownGood config, depending on whether attempting to use the Assigned config results in an error.
    #[serde(rename = "active", default, skip_serializing_if = "Option::is_none")]
    pub active: Option<crate::io::k8s::api::core::v1::NodeConfigSource>,

    /// Assigned reports the checkpointed config the node will try to use. When Node.Spec.ConfigSource is updated, the node checkpoints the associated config payload to local disk, along with a record indicating intended config. The node refers to this record to choose its config checkpoint, and reports this record in Assigned. Assigned only updates in the status after the record has been checkpointed to disk. When the Kubelet is restarted, it tries to make the Assigned config the Active config by loading and validating the checkpointed payload identified by Assigned.
    #[serde(rename = "assigned", default, skip_serializing_if = "Option::is_none")]
    pub assigned: Option<crate::io::k8s::api::core::v1::NodeConfigSource>,

    /// Error describes any problems reconciling the Spec.ConfigSource to the Active config. Errors may occur, for example, attempting to checkpoint Spec.ConfigSource to the local Assigned record, attempting to checkpoint the payload associated with Spec.ConfigSource, attempting to load or validate the Assigned config, etc. Errors may occur at different points while syncing config. Earlier errors (e.g. download or checkpointing errors) will not result in a rollback to LastKnownGood, and may resolve across Kubelet retries. Later errors (e.g. loading or validating a checkpointed config) will result in a rollback to LastKnownGood. In the latter case, it is usually possible to resolve the error by fixing the config assigned in Spec.ConfigSource. You can find additional information for debugging by searching the error message in the Kubelet log. Error is a human-readable description of the error state; machines can check whether or not Error is empty, but should not rely on the stability of the Error text across Kubelet versions.
    #[serde(rename = "error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,

    /// LastKnownGood reports the checkpointed config the node will fall back to when it encounters an error attempting to use the Assigned config. The Assigned config becomes the LastKnownGood config when the node determines that the Assigned config is stable and correct. This is currently implemented as a 10-minute soak period starting when the local record of Assigned config is updated. If the Assigned config is Active at the end of this period, it becomes the LastKnownGood. Note that if Spec.ConfigSource is reset to nil (use local defaults), the LastKnownGood is also immediately reset to nil, because the local default config is always assumed good. You should not make assumptions about the node's method of determining config stability and correctness, as this may change or become configurable in the future.
    #[serde(rename = "lastKnownGood", default, skip_serializing_if = "Option::is_none")]
    pub last_known_good: Option<crate::io::k8s::api::core::v1::NodeConfigSource>,
}

/// NodeDaemonEndpoints lists ports opened by daemons running on the Node.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeDaemonEndpoints {
    /// Endpoint on which Kubelet is listening.
    #[serde(rename = "kubeletEndpoint", default, skip_serializing_if = "Option::is_none")]
    pub kubelet_endpoint: Option<crate::io::k8s::api::core::v1::DaemonEndpoint>,
}

/// NodeFeatures describes the set of features implemented by the CRI implementation. The features contained in the NodeFeatures should depend only on the cri implementation independent of runtime handlers.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeFeatures {
    /// SupplementalGroupsPolicy is set to true if the runtime supports SupplementalGroupsPolicy and ContainerUser.
    #[serde(rename = "supplementalGroupsPolicy", default, skip_serializing_if = "Option::is_none")]
    pub supplemental_groups_policy: Option<bool>,
}

/// NodeList is the whole list of all Nodes which have been registered with master.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeList {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    ///
    /// Allowed values: `v1`.
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// List of nodes
    #[serde(rename = "items", default, skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::io::k8s::api::core::v1::Node>>,

    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    ///
    /// Allowed values: `NodeList`.
    #[serde(rename = "kind", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,

    /// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::ListMeta>,
}

impl NodeList {
    /// The apiVersion of this resource.
    pub const API_VERSION: &'static str = "v1";

    /// The kind of this resource.
    pub const KIND: &'static str = "NodeList";
}

impl Default for NodeList {
    fn default() -> Self {
        Self {
            api_version: Some(Self::API_VERSION.to_string()),
            items: None,
            kind: Some(Self::KIND.to_string()),
            metadata: None,
        }
    }
}

/// NodePodPreemptionPolicy defines the node-level policies governing preemption for pods on this node.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodePodPreemptionPolicy {
    /// DisableResizePreemption lists the owners (e.g., autoscalers, operators, administrators) that have requested to disable scheduler and Kubelet preemption for in-place pod resize on this node. If this list is non-empty, resize-induced preemption is disabled on this node. This is an alpha field and requires enabling the InPlacePodVerticalScalingSchedulerPreemption feature gate.
    #[serde(rename = "disableResizePreemption", default, skip_serializing_if = "Option::is_none")]
    pub disable_resize_preemption: Option<Vec<String>>,
}

/// NodeRuntimeHandler is a set of runtime handler information.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeRuntimeHandler {
    /// Supported features.
    #[serde(rename = "features", default, skip_serializing_if = "Option::is_none")]
    pub features: Option<crate::io::k8s::api::core::v1::NodeRuntimeHandlerFeatures>,

    /// Runtime handler name. Empty for the default runtime handler.
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// NodeRuntimeHandlerFeatures is a set of features implemented by the runtime handler.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeRuntimeHandlerFeatures {
    /// RecursiveReadOnlyMounts is set to true if the runtime handler supports RecursiveReadOnlyMounts.
    #[serde(rename = "recursiveReadOnlyMounts", default, skip_serializing_if = "Option::is_none")]
    pub recursive_read_only_mounts: Option<bool>,

    /// UserNamespaces is set to true if the runtime handler supports UserNamespaces, including for volumes.
    #[serde(rename = "userNamespaces", default, skip_serializing_if = "Option::is_none")]
    pub user_namespaces: Option<bool>,
}

/// A node selector represents the union of the results of one or more label queries over a set of nodes; that is, it represents the OR of the selectors represented by the node selector terms.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeSelector {
    /// Required. A list of node selector terms. The terms are ORed.
    #[serde(rename = "nodeSelectorTerms", default, skip_serializing_if = "Option::is_none")]
    pub node_selector_terms: Option<Vec<crate::io::k8s::api::core::v1::NodeSelectorTerm>>,
}

/// A node selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeSelectorRequirement {
    /// The label key that the selector applies to.
    #[serde(rename = "key", default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,

    /// Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
    #[serde(rename = "operator", default, skip_serializing_if = "Option::is_none")]
    pub operator: Option<String>,

    /// An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.
    #[serde(rename = "values", default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

/// A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeSelectorTerm {
    /// A list of node selector requirements by node's labels.
    #[serde(rename = "matchExpressions", default, skip_serializing_if = "Option::is_none")]
    pub match_expressions: Option<Vec<crate::io::k8s::api::core::v1::NodeSelectorRequirement>>,

    /// A list of node selector requirements by node's fields.
    #[serde(rename = "matchFields", default, skip_serializing_if = "Option::is_none")]
    pub match_fields: Option<Vec<crate::io::k8s::api::core::v1::NodeSelectorRequirement>>,
}

/// NodeSpec describes the attributes that a node is created with.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeSpec {
    /// Deprecated: Previously used to specify the source of the node's configuration for the DynamicKubeletConfig feature. This feature is removed.
    #[serde(rename = "configSource", default, skip_serializing_if = "Option::is_none")]
    pub config_source: Option<crate::io::k8s::api::core::v1::NodeConfigSource>,

    /// Deprecated. Not all kubelets will set this field. Remove field after 1.13. see: https://issues.k8s.io/61966
    #[serde(rename = "externalID", default, skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,

    /// PodCIDR represents the pod IP range assigned to the node.
    #[serde(rename = "podCIDR", default, skip_serializing_if = "Option::is_none")]
    pub pod_cidr: Option<String>,

    /// podCIDRs represents the IP ranges assigned to the node for usage by Pods on that node. If this field is specified, the 0th entry must match the podCIDR field. It may contain at most 1 value for each of IPv4 and IPv6.
    #[serde(rename = "podCIDRs", default, skip_serializing_if = "Option::is_none")]
    pub pod_cidrs: Option<Vec<String>>,

    /// PodPreemptionPolicy controls the node-level preemption behaviors for pods on this node. This is an alpha field and requires enabling the InPlacePodVerticalScalingSchedulerPreemption feature gate.
    #[serde(rename = "podPreemptionPolicy", default, skip_serializing_if = "Option::is_none")]
    pub pod_preemption_policy: Option<crate::io::k8s::api::core::v1::NodePodPreemptionPolicy>,

    /// ID of the node assigned by the cloud provider in the format: <ProviderName>://<ProviderSpecificNodeID>
    #[serde(rename = "providerID", default, skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<String>,

    /// If specified, the node's taints.
    #[serde(rename = "taints", default, skip_serializing_if = "Option::is_none")]
    pub taints: Option<Vec<crate::io::k8s::api::core::v1::Taint>>,

    /// Unschedulable controls node schedulability of new pods. By default, node is schedulable. More info: https://kubernetes.io/docs/concepts/nodes/node/#manual-node-administration
    #[serde(rename = "unschedulable", default, skip_serializing_if = "Option::is_none")]
    pub unschedulable: Option<bool>,
}

/// NodeStatus is information about the current status of a node.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeStatus {
    /// List of addresses reachable to the node. Queried from cloud provider, if available. More info: https://kubernetes.io/docs/reference/node/node-status/#addresses Note: This field is declared as mergeable, but the merge key is not sufficiently unique, which can cause data corruption when it is merged. Callers should instead use a full-replacement patch. See https://pr.k8s.io/79391 for an example. Consumers should assume that addresses can change during the lifetime of a Node. However, there are some exceptions where this may not be possible, such as Pods that inherit a Node's address in its own status or consumers of the downward API (status.hostIP).
    #[serde(rename = "addresses", default, skip_serializing_if = "Option::is_none")]
    pub addresses: Option<Vec<crate::io::k8s::api::core::v1::NodeAddress>>,

    /// Allocatable represents the resources of a node that are available for scheduling. Defaults to Capacity.
    #[serde(rename = "allocatable", default, skip_serializing_if = "Option::is_none")]
    pub allocatable: Option<std::collections::BTreeMap<String, crate::io::k8s::apimachinery::pkg::api::resource::Quantity>>,

    /// Capacity represents the total resources of a node. More info: https://kubernetes.io/docs/reference/node/node-status/#capacity
    #[serde(rename = "capacity", default, skip_serializing_if = "Option::is_none")]
    pub capacity: Option<std::collections::BTreeMap<String, crate::io::k8s::apimachinery::pkg::api::resource::Quantity>>,

    /// Conditions is an array of current observed node conditions. More info: https://kubernetes.io/docs/reference/node/node-status/#condition
    #[serde(rename = "conditions", default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::io::k8s::api::core::v1::NodeCondition>>,

    /// Status of the config assigned to the node via the dynamic Kubelet config feature.
    #[serde(rename = "config", default, skip_serializing_if = "Option::is_none")]
    pub config: Option<crate::io::k8s::api::core::v1::NodeConfigStatus>,

    /// Endpoints of daemons running on the Node.
    #[serde(rename = "daemonEndpoints", default, skip_serializing_if = "Option::is_none")]
    pub daemon_endpoints: Option<crate::io::k8s::api::core::v1::NodeDaemonEndpoints>,

    /// DeclaredFeatures represents the features related to feature gates that are declared by the node.
    #[serde(rename = "declaredFeatures", default, skip_serializing_if = "Option::is_none")]
    pub declared_features: Option<Vec<String>>,

    /// Features describes the set of features implemented by the CRI implementation.
    #[serde(rename = "features", default, skip_serializing_if = "Option::is_none")]
    pub features: Option<crate::io::k8s::api::core::v1::NodeFeatures>,

    /// List of container images on this node
    #[serde(rename = "images", default, skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<crate::io::k8s::api::core::v1::ContainerImage>>,

    /// Set of ids/uuids to uniquely identify the node. More info: https://kubernetes.io/docs/reference/node/node-status/#info
    #[serde(rename = "nodeInfo", default, skip_serializing_if = "Option::is_none")]
    pub node_info: Option<crate::io::k8s::api::core::v1::NodeSystemInfo>,

    /// NodePhase is the recently observed lifecycle phase of the node. More info: https://kubernetes.io/docs/concepts/nodes/node/#phase The field is never populated, and now is deprecated.
    #[serde(rename = "phase", default, skip_serializing_if = "Option::is_none")]
    pub phase: Option<String>,

    /// The available runtime handlers.
    #[serde(rename = "runtimeHandlers", default, skip_serializing_if = "Option::is_none")]
    pub runtime_handlers: Option<Vec<crate::io::k8s::api::core::v1::NodeRuntimeHandler>>,

    /// List of volumes that are attached to the node.
    #[serde(rename = "volumesAttached", default, skip_serializing_if = "Option::is_none")]
    pub volumes_attached: Option<Vec<crate::io::k8s::api::core::v1::AttachedVolume>>,

    /// List of attachable volumes in use (mounted) by the node.
    #[serde(rename = "volumesInUse", default, skip_serializing_if = "Option::is_none")]
    pub volumes_in_use: Option<Vec<String>>,
}

/// NodeSwapStatus represents swap memory information.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeSwapStatus {
    /// Total amount of swap memory in bytes.
    #[serde(rename = "capacity", default, skip_serializing_if = "Option::is_none")]
    pub capacity: Option<i64>,
}

/// NodeSystemInfo is a set of ids/uuids to uniquely identify the node.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct NodeSystemInfo {
    /// The Architecture reported by the node
    #[serde(rename = "architecture", default, skip_serializing_if = "Option::is_none")]
    pub architecture: Option<String>,

    /// Boot ID reported by the node.
    #[serde(rename = "bootID", default, skip_serializing_if = "Option::is_none")]
    pub boot_id: Option<String>,

    /// ContainerRuntime Version reported by the node through runtime remote API (e.g. containerd://1.4.2).
    #[serde(rename = "containerRuntimeVersion", default, skip_serializing_if = "Option::is_none")]
    pub container_runtime_version: Option<String>,

    /// Kernel Version reported by the node from 'uname -r' (e.g. 3.16.0-0.bpo.4-amd64).
    #[serde(rename = "kernelVersion", default, skip_serializing_if = "Option::is_none")]
    pub kernel_version: Option<String>,

    /// Deprecated: KubeProxy Version reported by the node.
    #[serde(rename = "kubeProxyVersion", default, skip_serializing_if = "Option::is_none")]
    pub kube_proxy_version: Option<String>,

    /// Kubelet Version reported by the node.
    #[serde(rename = "kubeletVersion", default, skip_serializing_if = "Option::is_none")]
    pub kubelet_version: Option<String>,

    /// MachineID reported by the node. For unique machine identification in the cluster this field is preferred. Learn more from man(5) machine-id: http://man7.org/linux/man-pages/man5/machine-id.5.html
    #[serde(rename = "machineID", default, skip_serializing_if = "Option::is_none")]
    pub machine_id: Option<String>,

    /// The Operating System reported by the node
    #[serde(rename = "operatingSystem", default, skip_serializing_if = "Option::is_none")]
    pub operating_system: Option<String>,

    /// OS Image reported by the node from /etc/os-release (e.g. Debian GNU/Linux 7 (wheezy)).
    #[serde(rename = "osImage", default, skip_serializing_if = "Option::is_none")]
    pub os_image: Option<String>,

    /// Whether the node is running in a user namespace.
    #[serde(rename = "runningInUserNamespace", default, skip_serializing_if = "Option::is_none")]
    pub running_in_user_namespace: Option<bool>,

    /// Swap Info reported by the node.
    #[serde(rename = "swap", default, skip_serializing_if = "Option::is_none")]
    pub swap: Option<crate::io::k8s::api::core::v1::NodeSwapStatus>,

    /// SystemUUID reported by the node. For unique machine identification MachineID is preferred. This field is specific to Red Hat hosts https://access.redhat.com/documentation/en-us/red_hat_subscription_management/1/html/rhsm/uuid
    #[serde(rename = "systemUUID", default, skip_serializing_if = "Option::is_none")]
    pub system_uuid: Option<String>,
}
