// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ObjectFieldSelector selects an APIVersioned field of an object.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ObjectFieldSelector {
    /// Version of the schema the FieldPath is written in terms of, defaults to "v1".
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,

    /// Path of the field to select in the specified API version.
    #[serde(rename = "fieldPath", default, skip_serializing_if = "Option::is_none")]
    pub field_path: Option<String>,
}
