// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// PortworxVolumeSource represents a Portworx volume resource.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PortworxVolumeSource {
    /// fSType represents the filesystem type to mount Must be a filesystem type supported by the host operating system. Ex. "ext4", "xfs". Implicitly inferred to be "ext4" if unspecified.
    #[serde(rename = "fsType", default, skip_serializing_if = "Option::is_none")]
    pub fs_type: Option<String>,

    /// readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
    #[serde(rename = "readOnly", default, skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,

    /// volumeID uniquely identifies a Portworx volume
    #[serde(rename = "volumeID", default, skip_serializing_if = "Option::is_none")]
    pub volume_id: Option<String>,
}
