// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// Represents a projected volume source
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ProjectedVolumeSource {
    /// defaultMode are the mode bits used to set permissions on created files by default. Must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
    #[serde(rename = "defaultMode", default, skip_serializing_if = "Option::is_none")]
    pub default_mode: Option<i32>,

    /// defaultUser is Optional: The owner UID of the created files by default. The defaultUser field is only used as a fallback when the item-level user field is unset. (Alpha) This field requires the AtomicWriteVolumeUserFields feature gate to be enabled.
    #[serde(rename = "defaultUser", default, skip_serializing_if = "Option::is_none")]
    pub default_user: Option<i64>,

    /// sources is the list of volume projections. Each entry in this list handles one source.
    #[serde(rename = "sources", default, skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<crate::io::k8s::api::core::v1::VolumeProjection>>,
}
