// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ResourceRequirements describes the compute resource requirements.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResourceRequirements {
    /// Claims lists the names of resources, defined in spec.resourceClaims, that are used by this container.
    ///
    /// This field depends on the DynamicResourceAllocation feature gate.
    ///
    /// This field is immutable. It can only be set for containers.
    #[serde(rename = "claims", default, skip_serializing_if = "Option::is_none")]
    pub claims: Option<Vec<crate::io::k8s::api::core::v1::ResourceClaim>>,

    /// Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    #[serde(rename = "limits", default, skip_serializing_if = "Option::is_none")]
    pub limits: Option<std::collections::BTreeMap<String, crate::io::k8s::apimachinery::pkg::api::resource::Quantity>>,

    /// Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. Requests cannot exceed Limits. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    #[serde(rename = "requests", default, skip_serializing_if = "Option::is_none")]
    pub requests: Option<std::collections::BTreeMap<String, crate::io::k8s::apimachinery::pkg::api::resource::Quantity>>,
}
