// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ScaleIOVolumeSource represents a persistent ScaleIO volume
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ScaleIOVolumeSource {
    /// fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. "ext4", "xfs", "ntfs". Default is "xfs".
    #[serde(rename = "fsType", default, skip_serializing_if = "Option::is_none")]
    pub fs_type: Option<String>,

    /// gateway is the host address of the ScaleIO API Gateway.
    #[serde(rename = "gateway", default, skip_serializing_if = "Option::is_none")]
    pub gateway: Option<String>,

    /// protectionDomain is the name of the ScaleIO Protection Domain for the configured storage.
    #[serde(rename = "protectionDomain", default, skip_serializing_if = "Option::is_none")]
    pub protection_domain: Option<String>,

    /// readOnly Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
    #[serde(rename = "readOnly", default, skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,

    /// secretRef references to the secret for ScaleIO user and other sensitive information. If this is not provided, Login operation will fail.
    #[serde(rename = "secretRef", default, skip_serializing_if = "Option::is_none")]
    pub secret_ref: Option<crate::io::k8s::api::core::v1::LocalObjectReference>,

    /// sslEnabled Flag enable/disable SSL communication with Gateway, default false
    #[serde(rename = "sslEnabled", default, skip_serializing_if = "Option::is_none")]
    pub ssl_enabled: Option<bool>,

    /// storageMode indicates whether the storage for a volume should be ThickProvisioned or ThinProvisioned. Default is ThinProvisioned.
    #[serde(rename = "storageMode", default, skip_serializing_if = "Option::is_none")]
    pub storage_mode: Option<String>,

    /// storagePool is the ScaleIO Storage Pool associated with the protection domain.
    #[serde(rename = "storagePool", default, skip_serializing_if = "Option::is_none")]
    pub storage_pool: Option<String>,

    /// system is the name of the storage system as configured in ScaleIO.
    #[serde(rename = "system", default, skip_serializing_if = "Option::is_none")]
    pub system: Option<String>,

    /// volumeName is the name of a volume already created in the ScaleIO system that is associated with this volume source.
    #[serde(rename = "volumeName", default, skip_serializing_if = "Option::is_none")]
    pub volume_name: Option<String>,
}
