// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// A scoped-resource selector requirement is a selector that contains values, a scope name, and an operator that relates the scope name and values.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ScopedResourceSelectorRequirement {
    /// Represents a scope's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist.
    #[serde(rename = "operator", default, skip_serializing_if = "Option::is_none")]
    pub operator: Option<String>,

    /// The name of the scope that the selector applies to.
    #[serde(rename = "scopeName", default, skip_serializing_if = "Option::is_none")]
    pub scope_name: Option<String>,

    /// An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
    #[serde(rename = "values", default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}
