// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// SessionAffinityConfig represents the configurations of session affinity.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SessionAffinityConfig {
    /// clientIP contains the configurations of Client IP based session affinity.
    #[serde(rename = "clientIP", default, skip_serializing_if = "Option::is_none")]
    pub client_ip: Option<crate::io::k8s::api::core::v1::ClientIPConfig>,
}
