// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// SleepAction describes a "sleep" action.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SleepAction {
    /// Seconds is the number of seconds to sleep.
    #[serde(rename = "seconds", default, skip_serializing_if = "Option::is_none")]
    pub seconds: Option<i64>,
}
