// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// The node this Taint is attached to has the "effect" on any pod that does not tolerate the Taint.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Taint {
    /// Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
    #[serde(rename = "effect", default, skip_serializing_if = "Option::is_none")]
    pub effect: Option<String>,

    /// Required. The taint key to be applied to a node.
    #[serde(rename = "key", default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,

    /// TimeAdded represents the time at which the taint was added.
    #[serde(rename = "timeAdded", default, skip_serializing_if = "Option::is_none")]
    pub time_added: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::Time>,

    /// The taint value corresponding to the taint key.
    #[serde(rename = "value", default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}
