// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// TCPSocketAction describes an action based on opening a socket
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TCPSocketAction {
    /// Optional: Host name to connect to, defaults to the pod IP.
    #[serde(rename = "host", default, skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,

    /// Number or name of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
    #[serde(rename = "port", default, skip_serializing_if = "Option::is_none")]
    pub port: Option<crate::io::k8s::apimachinery::pkg::util::intstr::IntOrString>,
}
