// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// A topology selector requirement is a selector that matches given label. This is an alpha feature and may change in the future.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct TopologySelectorLabelRequirement {
    /// The label key that the selector applies to.
    #[serde(rename = "key", default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,

    /// An array of string values. One value must match the label to be selected. Each entry in Values is ORed.
    #[serde(rename = "values", default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}
