// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// VolumeStatus represents the status of a mounted volume. At most one of its members must be specified.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct VolumeStatus {
    /// image represents an OCI object (a container image or artifact) pulled and mounted on the kubelet's host machine.
    #[serde(rename = "image", default, skip_serializing_if = "Option::is_none")]
    pub image: Option<crate::io::k8s::api::core::v1::ImageVolumeStatus>,
}
