// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// VolumeHealthStatus contains health information for a volume reported by the CSI controller plugin.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct VolumeHealthStatus {
    /// conditions is the set of adverse conditions reported by the CSI controller plugin. An empty list means no adverse condition. At most 16 conditions may be reported.
    #[serde(rename = "healthConditions", default, skip_serializing_if = "Option::is_none")]
    pub health_conditions: Option<Vec<crate::io::k8s::api::core::v1::VolumeHealthCondition>>,

    /// lastTransitionTime is when the current set of conditions first appeared.
    #[serde(rename = "lastTransitionTime", default, skip_serializing_if = "Option::is_none")]
    pub last_transition_time: Option<crate::io::k8s::apimachinery::pkg::apis::meta::v1::Time>,
}
