// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// VolumeNodeAffinity defines constraints that limit what nodes this volume can be accessed from.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct VolumeNodeAffinity {
    /// required specifies hard node constraints that must be met.
    #[serde(rename = "required", default, skip_serializing_if = "Option::is_none")]
    pub required: Option<crate::io::k8s::api::core::v1::NodeSelector>,
}
