// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// The weights of all of the matched WeightedPodAffinityTerm fields are added per-node to find the most preferred node(s)
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WeightedPodAffinityTerm {
    /// Required. A pod affinity term, associated with the corresponding weight.
    #[serde(rename = "podAffinityTerm", default, skip_serializing_if = "Option::is_none")]
    pub pod_affinity_term: Option<crate::io::k8s::api::core::v1::PodAffinityTerm>,

    /// weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
    #[serde(rename = "weight", default, skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
}
