// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// HTTPIngressRuleValue is a list of http selectors pointing to backends. In the example: http://<host>/<path>?<searchpart> -> backend where where parts of the url correspond to RFC 3986, this resource will be used to match against everything after the last '/' and before the first '?' or '#'.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HTTPIngressRuleValue {
    /// paths is a collection of paths that map requests to backends.
    #[serde(rename = "paths", default, skip_serializing_if = "Option::is_none")]
    pub paths: Option<Vec<crate::io::k8s::api::networking::v1::HTTPIngressPath>>,
}
