// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// IPBlock describes a particular CIDR (Ex. "192.168.1.0/24","2001:db8::/64") that is allowed to the pods matched by a NetworkPolicySpec's podSelector. The except entry describes CIDRs that should not be included within this rule.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct IPBlock {
    /// cidr is a string representing the IPBlock Valid examples are "192.168.1.0/24" or "2001:db8::/64"
    #[serde(rename = "cidr", default, skip_serializing_if = "Option::is_none")]
    pub cidr: Option<String>,

    /// except is a slice of CIDRs that should not be included within an IPBlock Valid examples are "192.168.1.0/24" or "2001:db8::/64" Except values will be rejected if they are outside the cidr range
    #[serde(rename = "except", default, skip_serializing_if = "Option::is_none")]
    pub except: Option<Vec<String>>,
}
