// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ParentReference describes a reference to a parent object.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ParentReference {
    /// group is the group of the object being referenced.
    #[serde(rename = "group", default, skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,

    /// name is the name of the object being referenced.
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// namespace is the namespace of the object being referenced.
    #[serde(rename = "namespace", default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,

    /// resource is the resource of the object being referenced.
    #[serde(rename = "resource", default, skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
}
