// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.

/// ServiceBackendPort is the service port being referenced.
#[derive(Clone, Debug, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ServiceBackendPort {
    /// name is the name of the port on the Service. This is a mutually exclusive setting with "Number".
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// number is the numerical port number (e.g. 80) on the Service. This is a mutually exclusive setting with "Name".
    #[serde(rename = "number", default, skip_serializing_if = "Option::is_none")]
    pub number: Option<i32>,
}
